nelmio/NelmioApiDocBundle

Extractor/HandlerInterface.php

(avoid triggering warning on IDEs like PhpStorm

Fixed type annotations

---

Resources/views/layout.html.twig

suggested change in https://github.com/nelmio/NelmioApiDocBundle/pull/353 is not working

fix sandbox with host

---

Resources/public/css/screen.css
Resources/views/layout.html.twig
Tests/Parser/ValidationParserTest.php

Aloha!
I would like to have the ability to collapse certain sections of the json-response.
And i adjusted the ValidationParserTest, otherwise i got an error that `validator.mapping.class_metadata_factory` is not defined because it was removed after compiling the container due to RemovePrivateAliasesPass (running on sf2 v2.6.5)

[Feature] collapsible sections in json-response

---

.travis.yml

Use new Travis infrastructure. Test with PHP7.

---

composer.json

Bump Symfony requirements to 2.3

---

Extractor/AnnotationsProvider/DunglasApiProvider.php
Tests/Formatter/MarkdownFormatterTest.php
Tests/Formatter/SimpleFormatterTest.php

This is a micro-PR adding the `section` parameter for each DunglasApiBundle provided resource :

DunglasApiBundle : Add doc sections

---

Resources/doc/index.md

| Q             | A
| ------------- | ---
| Doc fix?      | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |
Small fix in ```index.md```.

[minor] Small doc fix in index.md

---

Resources/config/routing.yml

Fix mistake in #720

---

Twig/Extension/MarkdownExtension.php

Twig 2 compatibility

---

Parser/FormTypeParser.php
Tests/Fixtures/app/AppKernel.php
Tests/WebTestCase.php

Support Symfony 2.8+

---

.travis.yml
Tests/Fixtures/app/config/default.yml

This PR fixes a deprecation and test symfony 3.0 against a stable environment.

Fix a deprecation

---

Parser/DunglasApiParser.php
Tests/Fixtures/app/config/dunglas_api.yml

Fix #678.
Basically the patch of @marcin-piela

Handle circular references in DunglasApiParser

---

Resources/views/layout.html.twig

Added xhrFields: { withCredentials: true } to ajaxOptions to enable
browser authentication for cross origin API requests.

Added xhrFields: { withCredentials: true } to ajaxOptions

---

Parser/FormTypeParser.php

Bug has appeared when i migrate from symfony 2.8.1 to 2.8.2.
Must be related to https://github.com/symfony/symfony/pull/17162

Fix Collection Type options - Symfony 2.8 Support

---

Extractor/Handler/FosRestHandler.php
Tests/Extractor/Handler/FosRestHandlerTest.php
Tests/Fixtures/Controller/TestController.php
Tests/Fixtures/app/config/routing.yml

Fix Array to string conversion error on array requirements

---

Resources/public/css/screen.css
Resources/views/layout.html.twig
Resources/views/method.html.twig

Adding option to send data using textarea.
* This is very useful when you want to send long text.

Add textarea type for sandbox

---

Resources/views/method.html.twig

You could use JSON_UNESCAPED_UNICODE, to fix problem with cyrillic chars in docs

Fix problem with cyrillic chars in docs

---

Resources/views/layout.html.twig
Resources/views/method.html.twig

Fixed typo in js and added space in attributes

Little template fixes for sandbox

---

Resources/views/layout.html.twig
Resources/views/method.html.twig

I did a few small improvements to the sandbox that IMO makes it a little more usable.
- added request body (when relevant)
- added cURL command
Screenshots:
Sorry about the blur, I was testing with internal company API.

Adding request body and curl command to sandbox

---

Extractor/Handler/FosRestHandler.php
Tests/Extractor/Handler/FosRestHandlerTest.php
Tests/Fixtures/Controller/TestController.php
Tests/Fixtures/app/config/routing.yml

Patch for https://github.com/nelmio/NelmioApiDocBundle/issues/502 and a test for this case.

#502 hide requirement when empty

---

ModelDescriber/ObjectModelDescriber.php

Not sure about the solution though: I'm just skipping the declaration but maybe we want to do something else.

Do not use nullable result directly in ObjectModelDescriber

---

CONTRIBUTING.md
README.md

That's one of the last things to do before having something ready! I plan to release a beta soon.

[3.0] Document the bundle

---

Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/FunctionalTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1001

[Bug] Multiple nested @Response aren't accepted

---

Annotation/Model.php
Model/Model.php
ModelDescriber/CollectionModelDescriber.php
ModelDescriber/ObjectModelDescriber.php
SwaggerPhp/ModelRegister.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/Entity/Article.php
Tests/Functional/FunctionalTest.php
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php
Tests/Functional/WebTestCase.php
composer.json
phpunit.xml.dist

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1009

Add groups support

---

Controller/SwaggerUiController.php
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php

Fix docs when using FOSRestBundle format listener

---

DependencyInjection/NelmioApiDocExtension.php
ModelDescriber/FormModelDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/Form/DummyType.php
Tests/Functional/FunctionalTest.php
Tests/Functional/TestKernel.php
composer.json

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/956 and https://github.com/nelmio/NelmioApiDocBundle/issues/1019#issuecomment-310220592
Several types are supported. `CollectionType` is not one of them for now as it is a bit more complicated to support, I'd be happy to merge a PR adding its support though :)
Can you try it @magnetik @Alex-D @reneszabo ?

Add forms support

---

Annotation/Model.php
Controller/DocumentationController.php
DependencyInjection/NelmioApiDocExtension.php
Describer/SwaggerPhpDescriber.php
README.md
Resources/config/services.xml
SwaggerPhp/ModelRegister.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/Form/DummyType.php
Tests/Functional/FunctionalTest.php
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php
Tests/Functional/WebTestCase.php
Tests/Model/ModelRegistryTest.php
Tests/Routing/FilteredRouteCollectionBuilderTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1025

Add a controller exposing the documentation in json

---

DependencyInjection/Configuration.php
DependencyInjection/NelmioApiDocExtension.php
ModelDescriber/FormModelDescriber.php
ModelDescriber/JMSModelDescriber.php
README.md
Tests/Functional/Controller/JMSController.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/JMSFunctionalTest.php
Tests/Functional/TestKernel.php
Tests/Functional/WebTestCase.php
composer.json

Adds support for jms metadata.
This PR needs tests but I don't really know how to make them as I don't really use the jms serializer, could one of you help me on this?

Add JMS serializer support

---

Controller/DocumentationController.php
Controller/SwaggerUiController.php
Describer/ApiPlatformDescriber.php
Resources/config/api_platform.xml
Tests/Functional/SwaggerUiTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1032

Use request base url

---

Resources/doc/swagger-support.rst

see http://symfony.com/doc/build_errors

fix section title markup

---

Resources/config/services.xml

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1021#issuecomment-316588620

Execute the CollectionModelDescriber earlier

---

SwaggerPhp/ModelRegister.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1065

Fix the invalid reference notice

---

ModelDescriber/FormModelDescriber.php
Tests/Functional/Form/DummyType.php
Tests/Functional/FunctionalTest.php

This PR add support for CheckboxType

Add support for boolean type for CheckboxType

---

README.md

I noticed you released v3.0.0 :tada:. Thnx for the great work!

Remove beta warning from README.md

---

DependencyInjection/Compiler/ConfigurationPass.php
DependencyInjection/NelmioApiDocExtension.php
NelmioApiDocBundle.php

fix https://github.com/nelmio/NelmioApiDocBundle/issues/1149

Enable the FormModelDescriber only if forms are enabled

---

CHANGELOG.md

i suggest we also ask people who do pull requests to add their notes to the changelog to make it more manageable for people to know what is going on.

add changelog listing changes since 3.0

---

DependencyInjection/NelmioApiDocExtension.php
ModelDescriber/JMSModelDescriber.php

do not fail if phpdocumentor is not available

---

ModelDescriber/JMSModelDescriber.php
Tests/Functional/Controller/JMSController.php
Tests/Functional/Entity/JMSComplex.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/JMSFunctionalTest.php
composer.json

Fix complex groups context for jms models

---

Resources/views/method.html.twig

Fixes a wrap in the Response Section

Added Table Colspan to Response Status Code

---

Describer/ApiPlatformDescriber.php
composer.json

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1140, https://github.com/nelmio/NelmioApiDocBundle/issues/1128

Fix Api-Platform support

---

README.md
Resources/doc/index.rst
Tests/DependencyInjection/NelmioApiDocExtensionTest.php

Extracted from https://github.com/nelmio/NelmioApiDocBundle/pull/1169

Rework the docs

---

Resources/doc/index.rst

fix #1176
@GuilhemN is this correct?

Provide example for action summary and description

---

ModelDescriber/JMSModelDescriber.php
ModelDescriber/ObjectModelDescriber.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/Entity/User.php
Tests/Functional/JMSFunctionalTest.php

Add an exception to fail properly.
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1168#issuecomment-355964204

Add an exception

---

composer.json

allow phpdocumentor/reflection-docblock version ^4.0

---

Annotation/Security.php
CHANGELOG.md
Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/FunctionalTest.php
Tests/Functional/SwaggerUiTest.php

Added support for `@Security` annotations

---

RouteDescriber/RouteDescriberTrait.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1204

Add a missing variable initialisation

---

ModelDescriber/ObjectModelDescriber.php

Fix ObjectDescriber

---

Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/FunctionalTest.php
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1231 and https://github.com/nelmio/NelmioApiDocBundle/issues/1085#issuecomment-354111322

Support references to config definitions

---

ModelDescriber/Annotations/AnnotationsReader.php
ModelDescriber/Annotations/SwgAnnotationsReader.php
ModelDescriber/JMSModelDescriber.php
ModelDescriber/ObjectModelDescriber.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/Entity/User.php
Tests/Functional/FunctionalTest.php
Tests/Functional/JMSFunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1235

Allow to change a property name

---

CHANGELOG.md
DependencyInjection/Configuration.php
DependencyInjection/NelmioApiDocExtension.php
Resources/doc/areas.rst
Resources/doc/index.rst
Routing/FilteredRouteCollectionBuilder.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/Controller/JMSController.php
Tests/Functional/Controller/TestController.php
Tests/Functional/Controller/UndocumentedController.php
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php
Tests/Functional/WebTestCase.php
Tests/Routing/FilteredRouteCollectionBuilderTest.php
composer.json

|New feature? |yes   |
|Fixed tickets|#1121 |
**TODO:**
Closes #1121.

Allow to filter routes by host (#1121)

---

Resources/doc/index.rst

[Documentation] Add some examples about undocumented properties and annotations

---

CHANGELOG.md

|Bug fix?     |yes   |
|Fixed tickets|n/a   |

Use "areas" instead of "routes" in example for `nelmio_api_doc.areas` at `CHANGELOG.md`

---

Formatter/AbstractFormatter.php

I'm having this error at the moment I visit the NelmioApiDoc URL.
Notice: Undefined index: required
KernelException.php on line 57:
GetResponseForExceptionEvent {#1191 ▼
-exception: ContextErrorException {#3274 ▼
-context: array:7 [▶]
#message: "Notice: Undefined index: required"
#code: 0
#file: "/var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php"
#line: 75
#severity: E_NOTICE
trace: {▼
/var/www/api-onereach-basic/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php:75 {▼
› 'readonly'     => array_key_exists('readonly', $info) ? $info['readonly'] : null,
› 'required'     => $info['required'],
› 'default'      => array_key_exists('default', $info) ? $info['default'] : null,
} …

Solving error on this class

---

Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/ClassApiController.php
Tests/Functional/FunctionalTest.php
Tests/Functional/TestKernel.php

This should fix #993, at least partially. 
My need was to load `@Security` class wize.

Load class NelmioApiDocBundle annotations

---

ModelDescriber/JMSModelDescriber.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/JMSFunctionalTest.php

Doc: https://swagger.io/docs/specification/data-models/dictionaries/

Improve support for JMS dictionaries (associative arrays)

---

ModelDescriber/JMSModelDescriber.php
ModelDescriber/ObjectModelDescriber.php
Tests/Functional/Entity/CustomDateTime.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/JMSFunctionalTest.php

Normalize description for classes implementing `\DateTimeInterface`

---

Resources/doc/index.rst

Fix Model annotation example in docs

---

Resources/doc/faq.rst

* shared definitions
* optional path parameters

add more entries to the faq

---

ModelDescriber/FormModelDescriber.php
Tests/Functional/Form/ExtendedBuiltinType.php
Tests/Functional/Form/UserType.php
Tests/Functional/FunctionalTest.php

The same problem as in https://github.com/nelmio/NelmioApiDocBundle/pull/1304
I just tried to do it my way and I took into account the PR comments
The tests are the same as in the mentioned PR, just renamed

Support for extended builtin form types

---

Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/TestKernel.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1258

Support references to config parameters

---

ModelDescriber/FormModelDescriber.php
Tests/Functional/Form/EntityType.php
Tests/Functional/Form/UserType.php
Tests/Functional/FunctionalTest.php

I fixed a regression bug I introduced with my last PR which @phansys noticed.
Check https://github.com/nelmio/NelmioApiDocBundle/pull/1320/files#r187460288 for explanation

FormModelDescriber entity form type regression

---

.travis.yml
composer.json
phpunit

Run CI pipeline with PHP 7.2

---

RouteDescriber/FosRestDescriber.php
Tests/Functional/FunctionalTest.php

Put RequestParam annotations in body

---

Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1302, https://github.com/nelmio/NelmioApiDocBundle/pull/1308

Merge SWG annotations in manually created `@Operation`

---

Tests/Functional/Entity/Dummy.php

Closes https://github.com/nelmio/NelmioApiDocBundle/pull/1334

Fixes tests

---

RouteDescriber/FosRestDescriber.php

Leftover after https://github.com/nelmio/NelmioApiDocBundle/pull/1328

Remove unused variable

---

Resources/doc/faq.rst

i tiny tweak after #1357 to make sure the example in the faq works as is.

complete example for template in faq

---

DependencyInjection/Configuration.php
Tests/DependencyInjection/ConfigurationTest.php

jms/serializer can be nested, not just plain strings

Jms serializer groups can be nested

---

ModelDescriber/FormModelDescriber.php
Tests/Functional/FunctionalTest.php

Removed just line 179 and collectionType now working in example tab

CollectionType not working in example tab

---

ModelDescriber/ObjectModelDescriber.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1346 and closes https://github.com/nelmio/NelmioApiDocBundle/pull/1347

Support doctrine Collection

---

ModelDescriber/JMSModelDescriber.php
Tests/Functional/Entity/JMSUser.php
Tests/Functional/JMSFunctionalTest.php
composer.json

|Fixed tickets|n/a   |
Depends on https://github.com/GuilhemN/swagger/pull/10.
**TODO**

[JMSModelDescriber] [WIP] Allow to use free form objects from JMS serialization

---

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
Tests/Functional/Entity/SymfonyConstraints.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1388

AssertLength doesn't make the field required

---

RouteDescriber/FosRestDescriber.php
Tests/Functional/Form/DummyType.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1339

Respect the spec in the FosRestDescriber

---

ModelDescriber/ObjectModelDescriber.php
Tests/Functional/Entity/User.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1333

Ignore Type::$nullable

---

ModelDescriber/ObjectModelDescriber.php

Update to make trouble shooting easier with json error output enabled.

Update to make trouble shooting easier

---

Resources/config/services.xml

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1470

Do not autowire the form extension

---

README.md
UPGRADE-3.0.md

See https://github.com/nelmio/NelmioApiDocBundle/issues/1019

Add exceptions in the upgrading command to warn about the requirement to run it on 2.x

---

CONTRIBUTING.md
DependencyInjection/Configuration.php
DependencyInjection/NelmioApiDocExtension.php
Resources/doc/areas.rst
Routing/FilteredRouteCollectionBuilder.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/Routing/FilteredRouteCollectionBuilderTest.php

Added name_patterns filter option

---

RouteDescriber/FosRestDescriber.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1465

Fix map support of FOSRestBundle

---

Resources/doc/faq.rst

I've added question and answer about how to group similar routes in sections in the documentation. I find this is one of frequently asked questions which didn't have an answer. The screenshot shows what I mean: https://i.imgur.com/RnEMlB1.png . I'm not familiar with RST format, but I hope there is no errors in formatting.

Question about @SWG\Tag annotation added to FAQ

---

Controller/SwaggerUiController.php
Tests/Controller/ControllersTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1554

Allow Twig 3

---

.travis.yml
Tests/Functional/Controller/ApiController.php
Tests/Functional/Controller/FOSRestController.php
Tests/Functional/FOSRestTest.php
Tests/Functional/FunctionalTest.php
Tests/Functional/TestKernel.php

FOSRest does not support symfony 5 yet

remove FOSRest on symfony 5 test runs

---

RouteDescriber/FosRestDescriber.php
Tests/Functional/Controller/FOSRestController.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1585

Use FOSRest *Param::$key when defined

---

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php

https://github.com/nelmio/NelmioApiDocBundle/issues/1601

Fix generating example for Assert\Choice when choices are object not array

---

PropertyDescriber/ArrayPropertyDescriber.php

I didn't see a way here to get a class and property names, let it be at least title

Exception message fix for array properties

---

PropertyDescriber/ArrayPropertyDescriber.php

`$property->getTitle()` should be `$property->title`

Fix undefined function in OA\Schema

---

OpenApiPhp/ModelRegister.php

Fix undefined property `$this->mediaType`, should be mediaTypes

Fix undefined property `$this->mediaType`

---

OpenApiPhp/Util.php
Tests/Functional/TestKernel.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1650

Fix the Util class manipulation of array of objects

---

Describer/SwaggerPhpDescriber.php
Tests/Functional/Controller/InvokableController.php
Tests/Functional/FunctionalTest.php
Tests/Functional/TestKernel.php
composer.json

Support using annotations only at the class level of controllers

---

ModelDescriber/JMSModelDescriber.php
Tests/Functional/Entity/JMSComplex.php
Tests/Functional/JMSFunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1412

Add annotations support at methods level when using the JMS serializer

---

Command/DumpCommand.php
ModelDescriber/ObjectModelDescriber.php
OpenApiPhp/ModelRegister.php
OpenApiPhp/Util.php
Tests/Functional/TestKernel.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1691
Nested variables of the `Server` annotations were not taken into account leading to the linked issue.

Fix ServerVariable management

---

RouteDescriber/RouteMetadataDescriber.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1695

Fix a wrong use of operation->security

---

Resources/doc/index.rst

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1704

Update `@OA\Parameter` usage example

---

ModelDescriber/JMSModelDescriber.php
Tests/Functional/Entity/VirtualProperty.php

Ignore ReflectionException for "magic" JMS\Accessor methods

---

.gitattributes

Exclude development files from dist package.

Exclude development files from dist package

---

RouteDescriber/RouteMetadataDescriber.php
Tests/Functional/Controller/TestController.php
Tests/Functional/FunctionalTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1739

Fix the detection of references in the RouteMetadataDescriber

---

DependencyInjection/Compiler/ConfigurationPass.php
Form/Extension/DocumentationExtension.php
ModelDescriber/FormModelDescriber.php
Tests/Functional/Form/UserType.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1746

Allow to not document form types fields

---

ModelDescriber/ObjectModelDescriber.php
Tests/Functional/Entity/PrivateProtectedExposure.php
Tests/Functional/FunctionalTest.php
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1756

Fix exposure of private/protected methods

---

Describer/OpenApiPhpDescriber.php
Tests/Functional/Controller/ApiController.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1755

Fix a regression about manual paths in operation no longer being taken into account

---

DependencyInjection/Compiler/ConfigurationPass.php
DependencyInjection/NelmioApiDocExtension.php
Resources/config/fos_rest.xml
Resources/config/services.xml

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1754

Use annotations reader without cache

---

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php

Backport of https://github.com/nelmio/NelmioApiDocBundle/pull/1789

Added support for constraint attributes

---

phpunit.xml.dist

The current failures are fixed in #1792.

Let PHPUnit fail on warnings and risky tests

---

DependencyInjection/Configuration.php

See https://github.com/nelmio/NelmioApiDocBundle/pull/1457#issuecomment-796620190.

Backport #1457 for 2.x

---

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php

- Add minimum for GreaterThanOrEqual
- add minimum and exclusiveMinimum LessThanOrEqual annotation

feature: Add new validation from constraints.

---

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
Tests/Functional/Entity/SymfonyConstraints.php
Tests/Functional/FunctionalTest.php
Tests/Helper.php
Tests/ModelDescriber/Annotations/Fixture/CompoundStub.php
Tests/ModelDescriber/Annotations/Fixture/CompoundValidationRule.php
Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php
composer.json

Compound validation rule support

---

OpenApiPhp/Util.php
Tests/Functional/FunctionalTest.php
Tests/Functional/TestKernel.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1806

Fix additionalProperties support

---

Resources/doc/faq.rst

Fix the comment path from SwaggerUI to SwaggerUi since case does matter for template override to work.

Documentation : Update templates comment path for bundle override

---

Command/DumpCommand.php
Controller/DocumentationController.php
Controller/SwaggerUiController.php
Controller/YamlDocumentationController.php
Render/Html/AssetsMode.php
Render/Html/GetNelmioAsset.php
Render/Html/HtmlOpenApiRenderer.php
Render/Json/JsonOpenApiRenderer.php
Render/OpenApiRenderer.php
Render/RenderOpenApi.php
Render/Yaml/YamlOpenApiRenderer.php
Resources/config/services.xml
Resources/doc/commands.rst
Resources/doc/index.rst
Resources/views/SwaggerUi/index.html.twig
Tests/Command/DumpCommandTest.php
Tests/Render/Html/GetNelmioAssetTest.php
Tests/Render/RenderOpenApiTest.php

Closes https://github.com/nelmio/NelmioApiDocBundle/issues/1580

Dump documentation to a static HTML and YAML file

---

DependencyInjection/NelmioApiDocExtension.php
Render/Html/GetNelmioAsset.php
Render/Html/HtmlOpenApiRenderer.php
Render/RenderOpenApi.php
Resources/config/services.xml
Resources/views/SwaggerUi/index.html.twig
Tests/Render/Html/GetNelmioAssetTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1876 and https://github.com/nelmio/NelmioApiDocBundle/issues/1874

Fix support without twig

---

Model/ModelRegistry.php
PropertyDescriber/ArrayPropertyDescriber.php
PropertyDescriber/ObjectPropertyDescriber.php

Apply #1863 to 3.x branch

---

Model/ModelRegistry.php
Tests/Model/ModelRegistryTest.php

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1901

Fix usage of getCollectionValueTypes and getCollectionKeyTypes

---

Describer/OpenApiPhpDescriber.php
Tests/Functional/Controller/ApiController81.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1939

Add support of inline path parameters

---

Model/ModelRegistry.php
Tests/Model/ModelRegistryTest.php

Related to https://github.com/nelmio/NelmioApiDocBundle/issues/1977.

Improve "no describer found" error message

---

Resources/doc/index.rst

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1424#issuecomment-1131919500

Clarify default policy on routes

---

Resources/public/style.css
Resources/views/SwaggerUi/index.html.twig

Should fix https://github.com/nelmio/NelmioApiDocBundle/issues/1770

Remove Inline Styles in Favor of the Stylesheet

---

Controller/SwaggerUiController.php
Exception/RenderInvalidArgumentException.php
Render/RenderOpenApi.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/pull/1986

Catch a more precise exception in Swagger controller

---

Resources/doc/faq.rst

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1859#issuecomment-1150429043

Fix parameter sharing example

---

Resources/doc/index.rst

Replace "Symfony\Component\Serializer\Annotation\Group" by "Symfony\Component\Serializer\Annotation\Groups"

Update index.rst [Documentation]

---

Annotation/Model.php
OpenApiPhp/ModelRegister.php
Tests/Functional/Controller/ApiController80.php
Tests/Functional/Entity/ArticleInterface.php
composer.json
phpunit.xml.dist

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2023

Make Model Attachable

---

ApiDocGenerator.php
Controller/DocumentationController.php
Describer/OpenApiPhpDescriber.php
Tests/Functional/Resources/routes.yaml
Tests/Functional/SwaggerUiTest.php
Tests/Functional/TestKernel.php
Util/SetsContextTrait.php

Related to https://github.com/nelmio/NelmioApiDocBundle/issues/2022

Catch more precise exception in DocumentationController

---

Resources/doc/index.rst

Fix methods in route annotation in documentation

---

DependencyInjection/NelmioApiDocExtension.php
ModelDescriber/ObjectModelDescriber.php
Resources/config/services.xml

Fix https://github.com/nelmio/NelmioApiDocBundle/issues/2038

Make ClassMetadataFactory optional

---

Resources/doc/index.rst

add square close braket  in sample

Fix documentation

---

Routing/FilteredRouteCollectionBuilder.php

defaultRouteDisabled to handle attributes

---

composer.json

add support for doctrine/annotations 2.0

---

Annotation/Areas.php

https://github.com/nelmio/NelmioApiDocBundle/issues/2086

[FIX: #2086] Add Attribute::TARGET_CLASS for Areas attribute

---

Render/Json/JsonOpenApiRenderer.php
Tests/Command/DumpCommandTest.php

Fix for [2139](https://github.com/nelmio/NelmioApiDocBundle/issues/2139)

fix-2139: do not escape slashes

---

Model/Model.php

fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2172

use string instead of constant

---

PropertyDescriber/ObjectPropertyDescriber.php
Tests/Functional/Entity/Article81.php
Tests/Functional/FunctionalTest.php

fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2177

fix: describe nullable enums with allOf

---

Processor/NullablePropertyProcessor.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2187

fix-2187: Check if schema is available

---

Processors/MapQueryStringProcessor.php
RouteDescriber/RouteArgumentDescriber/SymfonyMapQueryStringDescriber.php
Tests/Functional/Controller/ApiController81.php
Tests/Functional/Entity/QueryModel/FilterQueryModel.php
Tests/Functional/Entity/QueryModel/PaginationQueryModel.php
Tests/Functional/Entity/QueryModel/SortEnum.php
Tests/Functional/Entity/QueryModel/SortQueryModel.php
Tests/Functional/SymfonyFunctionalTest.php
phpunit-baseline.json

fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2194

fix describing multiple map query string attributes

---

DependencyInjection/Compiler/CustomProcessorPass.php

Found when testing https://github.com/nelmio/NelmioApiDocBundle/issues/2191

feat: sort processors by priority

---

PropertyDescriber/ArrayPropertyDescriber.php
PropertyDescriber/PropertyDescriber.php
Tests/Functional/Entity/CompoundEntity.php
Tests/Functional/FunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2200

use hash to determine unique types

---

Processors/MapQueryStringProcessor.php
RouteDescriber/RouteArgumentDescriber/SymfonyMapQueryParameterDescriber.php
Tests/Functional/Controller/ApiController81.php
Tests/Functional/Entity/QueryModel/ArrayQueryModel.php
Tests/Functional/SymfonyFunctionalTest.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2202

fix-2022: Correctly describe array parameter

---

composer.json

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2163

Remove reference to nelm.io domain

---

Processor/MapRequestPayloadProcessor.php
Tests/Functional/Configs/CleanUnusedComponentsProcessor.yaml
Tests/Functional/ConfigurableContainerFactory.php
Tests/Functional/Controller/Controller2209.php
Tests/Functional/Controller/MapQueryStringController.php
Tests/Functional/ControllerKernel.php
Tests/Functional/ControllerTest.php
Tests/Functional/Fixtures/Controller2209.json
Tests/Functional/Fixtures/MapQueryStringCleanupComponents.json
Tests/Functional/Fixtures/MapQueryStringController.json
Tests/Functional/NelmioKernel.php
Tests/Functional/TestKernel.php

Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2209

fix-2209: Multiple @OA\MediaType() warning with MapRequestPayload

---

src/DependencyInjection/Configuration.php
src/Model/ModelRegistry.php
tests/Functional/Entity/SymfonyConstraints80.php
tests/Functional/Entity/SymfonyConstraints81.php

| New feature?  | no                                             |
| Deprecations? | no                                             |
This apply the rule [ReturnTypeFromReturnDirectArrayRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromreturndirectarrayrector)  over src and tests.

feat: apply rule ReturnTypeFromReturnDirectArrayRector from rector

---

.github/ISSUE_TEMPLATE/1_Bug_report.yaml

| Bug fix?      | yes/no                                                                                                                    |
| New feature?  | yes/no                                                                    |
| Deprecations? | yes/no                                                   |

docs: update 1_Bug_report.yaml

---

.github/ISSUE_TEMPLATE/1_Bug_report.yaml

| Bug fix?      | yes/no                                                                                                                    |
| New feature?  | yes/no                                                                    |
| Deprecations? | yes/no                                                   |

docs: fix 1_Bug_report.yaml

---

src/DependencyInjection/NelmioApiDocExtension.php

| New feature?  | no |
| Issues        | Fix #2291 |

fix(#2291): symfony 7.1 - deprecation Symfony\Component\HttpKernel\DependencyInjection\Extension

---

tests/Functional/Configs/AlternativeNamesPHP80Entities.yaml
tests/Functional/Configs/AlternativeNamesPHP81Entities.yaml
tests/Functional/Configs/CleanUnusedComponentsProcessor.yaml
tests/ModelDescriber/Annotations/AnnotationReaderTest.php
tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php

test: fix failing tests, enable CleanUnusedComponents processor

---

CHANGELOG.md

chore: prepare 4.30.0 release

---

CHANGELOG.md
docs/index.rst
src/ModelDescriber/JMSModelDescriber.php
tests/Functional/Configs/JMS.yaml
tests/Functional/Controller/JmsOptOutController.php
tests/Functional/ControllerTest.php
tests/Functional/Fixtures/JmsOptOutController.json

| New feature?  | yes                                                                    |
| Issues        | Fix #2056  #2341  |
Always registers `JMSModelDescriber` when the bundle is active, independently of the configured global `models.use_jms` option.
If `models.use_jms` is set, then …

feat(2056): support opt out of JMS serializer usage

---

tests/Functional/SwaggerPHPApiComplianceTest.php

chore: fix ci

---

docs/symfony_attributes.rst

Commit 7cb43890ed9fef66bde0e3cd0eab834286889750 moved the location of `RouteArgumentDescriberInterface.php`. This PR adjusts sources to changes.

docs: update RouteArgumentDescriberInterface reference

---

config/services.xml
phpstan-baseline.neon
src/ModelDescriber/ObjectModelDescriber.php
src/PropertyDescriber/PropertyDescriberInterface.php
src/PropertyDescriber/RequiredPropertyDescriber.php
tests/Functional/Fixtures/MapQueryStringCleanupComponents.json
tests/Functional/Fixtures/MapQueryStringController.json
tests/Functional/Fixtures/MapRequestPayloadController.json
tests/Functional/FunctionalTest.php
tests/Functional/ValidationGroupsFunctionalTest.php

| New feature?  | no                                                                 |
| Deprecations? |no                                                  |
Move the behaviour for determining required property.

refactor: determining property required logic 

---

phpstan-baseline.neon
src/PropertyDescriber/PropertyDescriberInterface.php

reverts potential breaking change introduced in https://github.com/nelmio/NelmioApiDocBundle/pull/2359

revert: bring back schema to interface

---

.github/workflows/continuous-integration.yml

Add `codecov/test-results-action` action to ci

ci: codecov test results

---

composer.json

Fix failing phpunit CI for 5.x

ci: 5.x phpunit ci fix

---

update-js.sh

https://github.com/nelmio/NelmioApiDocBundle/pull/2379#issuecomment-2461846588

fix: incorrect script destination

---

.github/dependabot.yml

ci: change interval to weekly

---

tests/Functional/Configs/EnableSerializer.yaml
tests/Functional/Controller/MapQueryStringController.php
tests/Functional/Controller/MapRequestPayloadArray.php
tests/Functional/Controller/MapRequestPayloadController.php
tests/Functional/ControllerTest.php
tests/Functional/Fixtures/MapQueryStringCleanupComponents.json
tests/Functional/Fixtures/MapQueryStringController.json
tests/Functional/Fixtures/MapRequestPayloadArray.json
tests/Functional/Fixtures/MapRequestPayloadController.json

Some attributes where not properly imported and the serializer was not enabled, so some tests were not doing what was expected (the actual code is fine).

test: fix missing import + serializer was not enabled when needed

---

.symfony.bundle.yaml

Update documentation config for 5.x

docs: update symfony documentation config for dev 5.x

---

README.md

docs: update README shields
