nelmio/NelmioApiDocBundle

Extractor/ApiDocExtractor.php, Parser/FormTypeParser.php, Resources/doc/index.md, Tests/Parser/FormTypeParserTest.php
Hi everybody.
Just a little PR to introduce form options into the `ApiDoc`.
For Exemple : 
```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
$builder
->add('nickname', 'text')
;
if ('POST' === $options['method']) {
$builder
->add('login', 'text')
->add('plainPassword', 'password')
;
}
}
```
```php
/**
* @ApiDoc(
*  section="Product",
*  input={
*      "class"="Organization\Api\Form\Type\ProductType",
*      "options"={"method": "POST"},
*  },
*  output={ ... }
* )
*/
public function createAction(Request $request, ...)
{
// ...
}
/**
* @ApiDoc(
*  section="Product",
*  input={
*      "class"="Organization\Api\Form\Type\ProductType",
*      "options"={"method": "PUT"},
*  },
*  output={ ... }
* )
*/
public function updateAction(Request $request, ...)
{
// ... …
```
=> Add form options to ApiDoc input

.travis.yml, DependencyInjection/AnnotationsProviderCompilerPass.php, DependencyInjection/LoadExtractorParsersPass.php, Extractor/AnnotationsProvider/DunglasJsonLdApiProvider.php, Extractor/AnnotationsProviderInterface.php, Extractor/ApiDocExtractor.php, Extractor/CachingApiDocExtractor.php, NelmioApiDocBundle.php, Parser/DunglasJsonLdApiParser.php, Resources/config/services.dunglas_json_ld_api.xml, Resources/config/services.xml, Tests/Extractor/AnnotationsProvider/DunglasJsonLdApiProviderTest.php, Tests/Extractor/ApiDocExtractorTest.php, Tests/Fixtures/Model/Popo.php, Tests/Fixtures/app/AppKernel.php, Tests/Fixtures/app/config/dunglas_json_ld_api.yml, Tests/Fixtures/app/config/dunglas_json_ld_api_routing.yml, Tests/Fixtures/app/config/routing.yml, Tests/Formatter/MarkdownFormatterTest.php, Tests/Formatter/SimpleFormatterTest.php, Tests/Formatter/SwaggerFormatterTest.php, Tests/Parser/DunglasJsonLdApiParserTest.php, Tests/Parser/FormTypeParserTest.php, composer.json
Adds support for https://github.com/dunglas/DunglasJsonLdApiBundle
It automatically generates the documentation from `Resource` definitions. As the bundle discourage the use of custom controllers, I've added a way to provides`ApiDoc` annotation instances without effectively annotating controllers (`AnnotationProviderInterface`).
Optimal config:
```yaml
nelmio_api_doc:
sandbox:
accept_type:        "application/json"
body_format:
formats:        [ "json" ]
default_format: "json"
request_format:
formats:
json:       "application/json"
```
TODO:
=> DunglasJsonLdApiBundle support

Resources/views/layout.html.twig
This fixes allows solve conflict with OAuth authentication (the empty access token override the granting)
=> fixes: not attaching `api_key` to query if empty

DependencyInjection/LoadExtractorParsersPass.php, Extractor/AnnotationsProvider/DunglasJsonLdApiProvider.php, Parser/DunglasJsonLdApiParser.php, Resources/config/services.dunglas_json_ld_api.xml
* Match the new bundle API
* Type now default to `string` if not automatically guessed (instead of an error before)
=> Fix DunglasJsonLdApiBundle support

Resources/views/layout.html.twig
I recently came across that when copying the prettified response there were no comma separating the elements. This solves this problem.
=> Add the commas to the prettified JSON

Resources/doc/index.md
I built a Symfony2 API without twig, so when I first added NelmioApiDocBundle it returned a not-rendered twig template, juste like https://github.com/nelmio/NelmioApiDocBundle/issues/350 . It took me some time to understand the issue so it might be worth a statement in the doc, to save other people's time).
=> Add documentation statement about twig dependency

Form/Extension/DescriptionFormTypeExtension.php
This PR fixes deprecated notices since SF 2.7.
Symfony 2.3+ BC kept.
=> Fix deprecated forms setDefaultOptions method

Parser/FormTypeParser.php
Hi.
Just a little fix.
When you use a form and you pass options to a subform, into documentation, options are not transmitted.
```php
class MyFrom extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{
$builder
->add('name', 'text')
->add('title', 'text')
->add('media', 'media', ['with_url' => false])
;
}
}
```
```php
class MediaType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{
if (true === $options['with_url']) {
$builder
->add('url', 'url')
;
}
if (true === $options['with_file']) {
$builder
->add('file', 'file')
;
}
}
}
```
=> Pass children options to subform

Resources/public/css/screen.css
Hello,
I have added styles for the ul and ol tags inside the content of an operation. You can see here the before:
An the after:
The change is straightforward, I think that it doesn't need more explanations :)
Regards!
=> Styles for lists inside .content

Command/DumpCommand.php, Tests/Command/DumpCommandTest.php, composer.json
Add _--view_ option to _api:doc:dump_ command to be able to dump docs only for provided view.
=> Add view option to api:doc:dump command

.travis.yml, composer.json
Also added `symfony/phpunit-bridge` to handle deprecated issues with ease.
Tests will fail because of deprecation (see #636).
Route config issues are solved on #614. I'll take look for form issues on another PR.
=> Include Symfony 2.7 stable on Travis and improve configuration

Extractor/Handler/FosRestHandler.php, Tests/Extractor/Handler/FosRestHandlerTest.php, Tests/Fixtures/Controller/TestController.php, Tests/Fixtures/app/config/routing.yml
It allows to display `[]` after a requirement when `array` is defined. 
Not a big fan of the duplication of `$annot->array` test, but was not fan of modifying `handleRequirements` for accepting the annotation directly (and not only the parameter)
=> Handle "array" parameter in FOSRestBundle QueryParam or RequestParam

Extractor/AnnotationsProvider/DunglasApiProvider.php
Filters were documented on every operations on the resource, but it does not make sense for operations on single entities.
@dunglas : Do you think it might be an issue retrieving the resource filters only for GET operations on collections ?
=> Only display filters on collections GET services

Form/Extension/DescriptionFormTypeExtension.php, Tests/Fixtures/Form/DependencyType.php, Tests/Fixtures/Form/EntityType.php, Tests/Fixtures/Form/ImprovedTestType.php, Tests/Fixtures/Form/RequireConstructionType.php, Tests/Fixtures/Form/TestType.php
Related to #636.
Symfony 2.3+ BC kept.
Failing test about routing configuration are fixed in #614.
=> Fix deprecated FormType::setDefaultOptions usage

Resources/views/layout.html.twig
Pipe symbol needs to be escaped in jQuery selector.
This symbol is added when multiple methods are allowed for a route.
e.g /api/doc#get|post--...
=> Added pipe to escaped symbols of jQuery selector

Parser/JsonSerializableParser.php, Parser/ValidationParser.php, Resources/config/services.xml, Resources/doc/index.md, Tests/Fixtures/Model/JsonSerializableOptionalConstructorTest.php, Tests/Fixtures/Model/JsonSerializableRequiredConstructorTest.php, Tests/Fixtures/Model/JsonSerializableTest.php, Tests/Parser/JsonSerializableParserTest.php
Adds a parser that adds information from the JSON generated from classes that are implement `JsonSerializable`
Also allows that same `input={"class"="Some\Class", "name"="class"}` syntax that can be used for forms to with data from JsonSerializable and validation information
=> Add support for JsonSerializable classes

Extractor/ApiDocExtractor.php
I don't know if this is intended or not, but `$info['subType']` was not defined after a clean installation. I'm using NelmioApiDocBundle with DunglasApiBundle.
=> Prevent error "Undefined index" when no subtype provided

composer.json
* Use the last beta version of ApiBundle to avoid BC break that will be merged soon in master
* Use the stable version of the Symfony Serializer Component
=> Prevent BC break in DunglasApiBundle

Extractor/CachingApiDocExtractor.php, Tests/Extractor/ApiDocExtractorTest.php, Tests/Extractor/CachingApiDocExtractorTest.php
This PR fixes issue when caching is enabled and _CachingApiDocExtractor_ saves cache only for the first view accessed. When other api doc views are requested same cache file with api doc data is used instead of creating and using different cache files for different views.
=> Fix CachingApiDocExtractor caches only first accessed view

Extractor/ApiDocExtractor.php
This patch allows the parser to properly obtain the `\ReflectionMethod` from a controller when declared as a service not specifying a method name but using a callable class instead.
http://symfony.com/doc/current/cookbook/controller/service.html#defining-the-controller-as-a-service
> 2.6: If your controller service implements the __invoke method, you can simply refer to the service id (app.hello_controller). 
Also, related to https://github.com/dunglas/DunglasApiBundle/issues/219
Failing tests aren't related AFAIK.
=> Fix ApiDocExtractor to accept callable classes as controllers

Resources/views/layout.html.twig
Reverts a previous fix for Firefox which is causing issues with Chrome and which is not necessary anymore for Firefox because they fixed the issue (https://bugzilla.mozilla.org/show_bug.cgi?id=477578)
Also Fixes #621
=> revert fix "LINK workaround for firefox"

composer.json
According to Travis, the min supported version is 5.4
=> composer: allow min PHP 5.4

Parser/FormTypeParser.php
With current master I noticed, that options given in an annotation are not passed through to the form instance any more. This worked for me since recent composer update. For me, this small change seems to solve the problem.
Just to give a little more detail, my annotation for a controller looked like this one:
/**
* @ApiDoc(
*     section = "Current User",
*     input = {
*         "class" = "AppBundle\Form\User\AddressForm",
*         "options" = {"disableTransformer" = true},
*         "name" = ""
*     },
*     statusCodes = {
*         201 = "Address created"
*     }
* )
*/
=> Options for form were not passed through

Extractor/ApiDocExtractor.php, Tests/Extractor/ApiDocExtractorTest.php, Tests/Fixtures/Controller/TestController.php, Tests/Fixtures/app/config/routing.yml
=> [ISSUE-739] ApiDoc parameters setting will override lower parameter definitions in the hierarchy

Extractor/ApiDocExtractor.php, Tests/Extractor/ApiDocExtractorTest.php
Empty string is now a valid default parameter value that is successfully merged with other parameters
Preventing access of uninitialized array key 'default'
Added functional test case for mergeParameters that covers this issue
=> Empty string is now a valid default parameter value

Parser/JsonSerializableParser.php, Tests/Parser/JsonSerializableParserTest.php
JSP is now able to set a default value for scalar types
This makes merging the parser result with other parser results easier
and gives some additional info when creating docs
=> Introduced default-value parameter to JsonSerializableParser

Annotation/ApiDoc.php, Tests/Extractor/ApiDocExtractorTest.php, Tests/Fixtures/Controller/TestController.php, Tests/Fixtures/app/config/default.yml, Tests/Fixtures/app/config/routing.yml, Tests/Formatter/testFormat-result-no-dunglas.markdown, Tests/Formatter/testFormat-result-no-dunglas.php, Tests/Formatter/testFormat-result.markdown, Tests/Formatter/testFormat-result.php
I have a routing file:
```yml
api_v1:
resource: "@ApiBundle/Resources/config/routing.yml"
prefix:   /v1
host:     api.{domain}
defaults:
domain: "%domain%"
requirements:
domain: "%domain%"
```
Currently documentation looks like this:
After this PR placeholder is replacement by default parameter:
=> Fix route host with placeholder

.travis.yml, Extractor/ApiDocExtractor.php, Extractor/Handler/FosRestHandler.php, Form/Extension/DescriptionFormTypeExtension.php, Parser/FormTypeParser.php, Parser/ValidationParser.php, Resources/config/services.xml, Tests/Fixtures/Controller/TestController.php, Tests/Fixtures/DependencyTypePath.php, Tests/Fixtures/Form/CollectionType.php, Tests/Fixtures/Form/CompoundType.php, Tests/Fixtures/Form/DependencyType.php, Tests/Fixtures/Form/EntityType.php, Tests/Fixtures/Form/ImprovedTestType.php, Tests/Fixtures/Form/RequireConstructionType.php, Tests/Fixtures/Form/RequiredType.php, Tests/Fixtures/Form/SimpleType.php, Tests/Fixtures/Form/TestType.php, Tests/Fixtures/RequestParamHelper.php, Tests/Fixtures/app/AppKernel.php, Tests/Fixtures/app/config/routing.yml, Tests/Fixtures/app/config/twig_assets.yml, Tests/Formatter/MarkdownFormatterTest.php, Tests/Formatter/testFormat-result-no-dunglas.markdown, Tests/Formatter/testFormat-result-no-dunglas.php, Tests/Formatter/testFormat-result.markdown, Tests/Formatter/testFormat-result.php, Tests/Parser/FormTypeParserTest.php, Util/LegacyFormHelper.php, composer.json
This PR adds symfony 3.0 support.
=> Add symfony 3.0 support

Annotation/ApiDoc.php, Tests/Annotation/ApiDocTest.php
We use the `defaults` parameters of a Route to add some information regarding reverse proxy strategy for example.
This PR avoid the `Array to string conversion` notice.
=> Avoid "array to string conversion" error

Command/DumpCommand.php
The dump command uses ContainerInterface::enterScope, which was deprecated in Symfony 2.8 and removed in 3.0.
=> Check for deprecated method enterScope() in DumpCommand

Extractor/Handler/FosRestHandler.php, Tests/Extractor/Handler/FosRestHandlerTest.php, Tests/Fixtures/Controller/TestController.php, Tests/Fixtures/app/config/routing.yml
FOSRestBundle QueryParam annotation allow array as a requirement, with keys "rule" and "error_message".
Fix https://github.com/nelmio/NelmioApiDocBundle/issues/773
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1015
=> Fix Array to string conversion error on array requirements

Parser/FormTypeParser.php
Fix to issue
https://github.com/nelmio/NelmioApiDocBundle/issues/798
There is a loop, and if there are few iterations, the previously defined $subForm variable causes wrong behaviour
=> Fixed bug with wrong form parsing when several custom inner types exist

Annotation/ApiDoc.php, Formatter/AbstractFormatter.php, Formatter/SimpleFormatter.php, Resources/views/method.html.twig
This PR adds an HTML view for the response map configuration.
Related issue:  #789
```php
/**
* @ApiDoc(
*     description = "Registers a new user",
*     section = "User",
*     https = true,
*     authentication = false,
*     input = {
*         "class" = RegistrationType::class,
*         "name" = ""
*     },
*     statusCodes = {
*         200 = "Success.",
*         400 = "Validation failed."
*     },
*     responseMap = {
*         200 = {
*             "class" = User::class,
*             "parsers" = {
*                 JmsMetadataParser::class
*             }
*         },
*         400 = {
*             "class" = RegistrationType::class,
*             "form_errors" = true,
*             "name" = ""
*         },
*     }
* )
*/
```
=> Use the response map in the html view

Command/DumpCommand.php
`hasOption` is confusingly named, it actually checks that the option has been created, not if the user has passed the option. So in this case its always true.
Also changed a weird usage of `in_array`.
=> Remove incorrect usage of hasOption

README.md
Link to ApiDoc documentation is now with ReST format instead of Markdown
=> Fixed link to documentation

Resources/views/method.html.twig
The labels of a field are usually translated. But this does not happen in the documentation.
=> Added translation to description

Resources/views/layout.html.twig
When using Vich uploader bundle null file value is used for preventing existing resource. If there is no file value, resource will be deleted.
=> Allow sending empty file data

Twig/Extension/MarkdownExtension.php
The `MarkdownExtra` class has quite some settings, but with the current setup, it's very cumbersome to set them.
The easiest way to achieve this, is by extending the `MarkdownExtension` and setting the properties directly on the instance referenced by `markdownParser`. Moving the `MarkdownExtra` instance to the DI makes no sense currently, because it doesn't really provide nice setters/getters and requires closures at some point.
So I see no point in the `markdownParser` property being private.
- If it stays private, I have to make my own class property and instance of the `MarkdownExtra` class. 
- If I want to override the `MarkdownExtension` right now, I have to copy more code, which could be avoided by extending the MarkdownExtension class and having access to the `markdownParser` …
=> Change visibility of markdownParser property to protected

Extractor/ApiDocExtractor.php
When we override templates, we sometimes need project related informations to appear in the documentation. So the **ApiDoc** annotation is not sufficient : we need to add variables to this class.
Solution : create a child class of ApiDoc. Then we also need to create a child class of the **ApiDocExtractor** to override the **ANNOTATION_CLASS** constant. And here comes the problem.
`self::ANNOTATION_CLASS` does not support inheritance
`static:ANNOTATION_CLASS` does
I think it could be a good improvement to help creating more complete documentations, with more project related details.
Thanks.
=> Allow custom ApiDoc annotation

Annotation/ApiDoc.php, Resources/doc/the-apidoc-annotation.rst, Resources/views/method.html.twig, Tests/Annotation/ApiDocTest.php
Sometimes it is neccessary to specify which headers will be accepted. These pull request solves that issue.
Headers are shown below parameters in their own section.
It is neccessary to specify only name for header.
``Description``, ``default``, ``required`` are optional parameters.
``Default`` parameter is used for sandbox, it will substitute value for header.
Screenshots:
https://www.evernote.com/l/AZCopjR4j4VDFLoXMmxY8HC9IBv0C5gJ7xY
https://www.evernote.com/l/AZB8tJgHiidCUJ0elPyYyctwtJssP4lTyPc
=> Headers support

Resources/public/css/screen.css, Resources/views/method.html.twig
For parameter types "array of choices" when we have very long format values, it's visible like that: 
After this PR, it will be looks like that:
=> Fix wrapping of format table row

Resources/doc/index.rst
I've added links to index.rst so the other doc files can be accessible directly, instead of hunting them down by hand in the doc directory.
This should also fix http://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html which, without the links, is a bit useless.
=> Links from index.rst to the other doc files

Resources/doc/index.rst
Some users have reported us that the links to other articles in this section are broken: http://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html#usage  I recommend to use a `toctree` directive because it's easier to maintain (for example the titles of the articles are updated automatically if they change).
=> Fixed the links to some doc articles

Resources/views/resources.html.twig
When I have a very rich API with many methods, the navigation between sections involves a lot of scrolling.
So I propose to add an index at the top of the page. Of course this will also require some styling (in my case, I fixed it at the bottom right of the page).
Thank you for any comments that may improve this PR.
=> Add navigation index for resources

Resources/doc/index.rst, Resources/doc/swagger-support.rst
This fixes #836 and the new doc build errors reported by symfony.com [here](http://symfony.com/doc/build_errors)
=> Fixed minor RST syntax issues in docs

.php_cs.dist, DependencyInjection/Compiler/AddRouteDescribersPass.php, DependencyInjection/Compiler/PriorityTaggedServiceTrait.php, Describer/RouteDescriber.php, Describer/SwaggerPhpDescriber.php, Resources/config/services.xml, Resources/config/swagger_php.xml, SwaggerPhp/OperationResolver.php, Tests/Describer/RouteDescriberTest.php, Tests/Fixtures/SwaggerPhp/Api.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/FunctionalTest.php, Util/ControllerReflector.php, composer.json
As @dbu suggested in [his article](https://blog.liip.ch/archive/2016/05/11/convert-nelmioapidocbundle-to-swagger-php.html), this PR allows to use SwaggerPhp annotations without specifying the path.
An example, before:
```php
/**
* @Route("/foo", method="GET")
* @SWG\Get(path="/foo")
*/
public function myAction()
{
}
```
After:
```php
/**
* @Route("/foo", method="GET")
* @SWG\Get()
*/
public function myAction()
{
}
```
=> [3.0] Allow implicit operations with SwaggerPhp annotations

Annotation/Model.php, ApiDocGenerator.php, DependencyInjection/Compiler/AddModelDescribersPass.php, Describer/DefaultDescriber.php, Describer/ModelRegistryAwareInterface.php, Describer/ModelRegistryAwareTrait.php, Describer/RouteDescriber.php, Describer/SwaggerPhpDescriber.php, EXSystApiDocBundle.php, Model/Model.php, Model/ModelRegistry.php, ModelDescriber/CollectionModelDescriber.php, ModelDescriber/ModelDescriberInterface.php, ModelDescriber/ObjectModelDescriber.php, ModelDescriber/ScalarModelDescriber.php, Resources/config/api_platform.xml, Resources/config/services.xml, Resources/config/swagger_php.xml, SwaggerPhp/AddDefaults.php, SwaggerPhp/ModelRegister.php, Tests/Describer/SwaggerPhpDescriberTest.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/Entity/Dummy.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php, Tests/Model/ModelRegistryTest.php, composer.json
Based on top of https://github.com/nelmio/NelmioApiDocBundle/pull/938 and https://github.com/nelmio/NelmioApiDocBundle/pull/937, this PR adds a `@Model` annotation that can be used with Swagger-php annotations as suggested in https://github.com/nelmio/NelmioApiDocBundle/issues/940:
```php
/**
* @Route("/users/{id}", methods={"GET"})
* @SWG\Response(
*     response="200",
*     description="User fetched.",
*     @Model(type="AppBundle\Entity\User")
* )
*/
public function getUserAction($id)
{
}
```
=> [3.0] Add a @Model annotation

DependencyInjection/Configuration.php, DependencyInjection/NelmioApiDocExtension.php, Tests/Functional/TestKernel.php
Fix for #947
The fact that the test are still passing with this change are the only test included :D
Maybe I should start testing the Extension?
=> Make source folder configurable

ModelDescriber/ScalarModelDescriber.php
No sure if there is a reason why it was not there in the first place. 
It's useful to me =)
=> Add support for bool type in ScalarModelDescriber

DependencyInjection/NelmioApiDocExtension.php
I just issued an error while installing NelmioApiDocBundle:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
The service "nelmio_api_doc.generator" has a dependency on a non-existent service "property_info". 
```
This is caused by the fact that symfony does not enable the `property_info` component integration by default.
=> Fix an error when installing NelmioApiDocBundle

RouteDescriber/FosRestDescriber.php
If the QueryParam is not nullable and strict, a 400 error will be raised if the query param is not raised, so it's required.
=> [3.0] Handle FOSRestBundle QueryParam required

Describer/SwaggerPhpDescriber.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/FunctionalTest.php
Fix https://github.com/nelmio/NelmioApiDocBundle/issues/965
Theorically this works fine but I wonder whether `exsyst/swagger` prints a valid file for operation tags as they must not be arrays.
=> Support @SWG\Tag

Routing/FilteredRouteCollectionBuilder.php, Tests/Routing/FilteredRouteCollectionBuilderTest.php
The rule of path_patterns config parameter is not obvious. This pull request changes the filter behavior of the route path_patterns. It makes a OR between pattern elements instead of a AND.
=> Change the behavior of path_patterns filter to use OR instead of AND

DependencyInjection/NelmioApiDocExtension.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1072
=> Remove SwaggerUI controller when TwigBundle is not registered

composer.json
`~7.0|~7.1` is the same as `~7.0`. I think you mean to do `7.0.*|7.1.*` since PHP does not do Semver.
=> Syntax update

Describer/ModelRegistryAwareTrait.php, ModelDescriber/FormModelDescriber.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/Form/UserType.php, Tests/Functional/FunctionalTest.php
1. Read form recursively (nested forms).
2.Added support for `EntityType` in `FormModelDescriber`. (if `multiple -> true` - array, not - string. Added examples).
2.Added support for `NumberType`.
3.Modified `formSupport` test.
fix https://github.com/nelmio/NelmioApiDocBundle/issues/1079
=> Reading form recursively down(nested form)

RouteDescriber/RouteMetadataDescriber.php, Tests/Functional/FunctionalTest.php
Currently symfony route requirements are mapped to swaggers' 'format' field on parameters. As described in the following links, the format is meant to be an extension upon the specified 'type' field. The requirements should be mapped to the 'pattern' field.
see:
[OpenAPI Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject)
[JSON Validation RFC](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3)
[OpenAPI Data Type Format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#dataTypeFormat)
=> fix: map route requirements to parameter pattern instead of format

Describer/DefaultDescriber.php
Starting from PHP 7.2 a warning will be thrown [when calling count() against non-countable objects](https://wiki.php.net/rfc/counting_non_countables).
This pull request attempts to fix a case where count() is called on a non-countable object - 
`\EXSyst\Component\Swagger\Collections\Responses` is not an array and doesn't implements `Countable`. Given it implements `Traversable`, the counting code is changed from `count()` to `iterator_count()`.
While the title states it as a compatibility fix, I suspect this also fixes a hidden bug.
=> PHP 7.2 compatibility fix

Resources/config/formatters.xml, Resources/config/services.xml, composer.json
Tests will be red because they already are, but the API Platform test suite pass with those changes. I suggest to merge this patch as is.
=> [2.x] Fix compatibility with Symfony 3.4 and 4.0

ModelDescriber/JMSModelDescriber.php, Tests/Functional/Controller/JMSController.php, Tests/Functional/Entity/VirtualProperty.php, Tests/Functional/JMSFunctionalTest.php, composer.json
Latest commit throws exception when attempting to read swagger annotation for virtual property
Nelmio\ApiDocBundle\ModelDescriber\SwaggerPropertyAnnotationReader::updateWithSwaggerPropertyAnnotation() must be an instance of ReflectionProperty, null given, called in D:\Work\php7\vendor\nelmio\api-doc-bundle\ModelDescriber\JMSModelDescriber.php on line 104
=> Fix exception when attempting to read swagger annotation for virtual property

ModelDescriber/JMSModelDescriber.php, ModelDescriber/ObjectModelDescriber.php, ModelDescriber/SwaggerPropertyAnnotationReader.php, Tests/Functional/Entity/JMSUser.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php, Tests/Functional/JMSFunctionalTest.php
The type invariation (changing from the real property to the sub items
definition) causes the swagger annotations to end up on the created
`Items` entry.
This changes the behaviour to update the real property entry with the
swagger annotation.
Additionally this ensures that "description", "title" and "example" are
only updated on `Schema` instances.
=> [3.0] Pass real property to swagger annotation reader

UPGRADE-3.0.md
Fix null argument
```php
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                                         
Type error: Argument 1 passed to SwaggerDocblockConvertCommand::escapeQuotes() must be of the type string, null given, called in SwaggerDocblockConvertCommand.php on line 92                   
```
=> Fix migration command

ModelDescriber/JMSModelDescriber.php, ModelDescriber/SwaggerPropertyAnnotationReader.php, Tests/Functional/Entity/JMSUser.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php, Tests/Functional/JMSFunctionalTest.php
I have done a few improvements
1. For jms model descriper added support type "int" alias of "intreger"
2. Reading "enum" and "default" from swagger property annotation
3. Fixed bug when data related to whole array was appended to its items. Just has found that this bug is already fixed in #1145 so i have stolen also improvements for SwaggerPropertyAnnotationReader from there.
=> Read more properties from swagger property annotation

UPGRADE-3.0.md
now that you have a stable release, people do not need to depend on the beta version anymore.
(and afaik composer recommends to use ^ rather than ~ when working with libraries that respect semver)
=> make upgrade instructions depend on stable version

ModelDescriber/FormModelDescriber.php, Tests/Functional/Form/DummyType.php, Tests/Functional/FunctionalTest.php
Integer support was missing so far.
=> [3.0] Add integer support to FormModelDescriber

DependencyInjection/NelmioApiDocExtension.php, ModelDescriber/JMSModelDescriber.php, ModelDescriber/PhpdocAnnotationReader.php, ModelDescriber/PhpdocPropertyAnnotationReader.php, README.md, Resources/config/services.xml, Tests/Functional/Entity/JMSUser.php, Tests/Functional/JMSFunctionalTest.php
The jms metadata model seems to not pick up descriptions. Imho we should pick them up, i played around with this code and hope for feedback. If the maintainers agree, i am happy to wrap up the pull request. Potentially it could also make sense to use the PhpdocAnnotationReader together with the form model generator, in case it does not pick all of the phpdoc.
=> parse phpdoc annotations in jms models

Describer/ApiPlatformDescriber.php
When I run fresh installation of NelmioApiDocBundle I have such error:
"Notice: Undefined variable: paths" in vendor/nelmio/api-doc-bundle/Describer/ApiPlatformDescriber.php:39
I look at the file and I saw that `$paths` variable is not defined, so I define it as empty array. Bundle with my fix works :)
=> Fix undefined variable  in ApiPlatformDescriber

Formatter/MarkdownFormatter.php
There is a little bug with the markdown generation by missing documentation. 
Adding the documentation section only when it's the same as the description does not make sense. So the documentation is missing when you create the markdown output.
This little tweak fixes it.
=> Fixing missing documentation on Markdown output

Resources/config/services.xml
The service was not defined public or private, which threw deprecation notices in the tests where we use it from the container. It is now declared public explicitly to not have deprecations.
=> Made nelmio_api_doc.generator a public service

DependencyInjection/NelmioApiDocExtension.php, ModelDescriber/JMSModelDescriber.php, ModelDescriber/ObjectModelDescriber.php, ModelDescriber/SwaggerDefinitionAnnotationReader.php, ModelDescriber/SwaggerPropertyAnnotationReader.php, Resources/config/services.xml, Tests/Functional/Entity/JMSComplex.php, Tests/Functional/Entity/JMSUser.php, Tests/Functional/Entity/User.php, Tests/Functional/JMSFunctionalTest.php
This PR aims to add some processing when using attributes for a Swagger property (using the JMS Serializer). In detail they are:
* `required` (as part of a `@SWG\Definition`)
* `minimum`
* `exclusiveMinimum`
* `maximum`
* `exclusiveMaximum`
* `minLength`
* `maxLength`
* `minItems`
* `maxItems`
* `uniqueItems`
* `multipleOf`
* `pattern`
=> Add some missing property attributes for JMS model describer

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
I found out that the Regex patterns are nullable which could trigger an exception. This fix will ignore patterns that are null.
=> Nullable patterns no longer throw exceptions

ModelDescriber/FormModelDescriber.php, Tests/Functional/Form/DummyType.php, Tests/Functional/FunctionalTest.php
When a form containing a ChoiceType field with option multiple set to true is used with the `Nelmio\ApiDocBundle\Annotation\Model` annotation, the field type is set to `string` instead of `array` in the api documentation.
This PR set the type to `array` ~~and add an example value of `[1, 2, 3]`~~.
=> FormModelDescriber: set type to array with correct example for multiple choices form.

Describer/ApiPlatformDescriber.php
|Fixed tickets|#1260 |
See https://github.com/nelmio/NelmioApiDocBundle/pull/1260/files#r175258427.
=> Respect invalid argument syntax used by PHP at `ApiPlatformDescriber::__construct()`

CHANGELOG.md, Resources/doc/faq.rst, Resources/doc/index.rst, SwaggerPhp/ModelRegister.php, Tests/Functional/Controller/ApiController.php, Tests/Swagger/ModelRegisterTest.php, UPGRADE-3.0.md, composer.json
Implements https://github.com/nelmio/NelmioApiDocBundle/issues/1254#issuecomment-373918345.
>Thinking about it again we could also use the ``ref`` field:
> ```php
> /**
>  * @Response(response=200,
>  *      @Schema(ref=@Model(type=""))
>  * )
>  */
> ```
> when it is not clear what ``@Model`` should be used for. That makes things much clearer imo.
> 
> > could it be possible to add a model field to zircote/swagger-php instead? that might be more straightforward and less confusing. but is only possible if the model field would make sense for zircote itself as well - but from how i understand things, it would make sense.
> 
> Well they use ``ref`` a lot, I don't think this would be accepted. Plus we would have no way to pass options as well (serialization groups for instance).
=> Support @Model through `ref`

UPGRADE-3.0.md
Changes:  
- Allowed null input in `escapeQuotes(string $str)` - description of an API can be null
- Added command option `views` to input comma separated list of views - the API can have view(s) other than `default`
---
HowToTest:  
- The command should work for APIs with no description
(Believe me! there are people who create APIs without description; but I can remove this change if you don't like it)
- The command should be able to take a comma separated list of views and convert docblocks for APIs of all those views
=> Updated SwaggerDocblockConvertCommand command in UPGRADE-3.0.md

RouteDescriber/FosRestDescriber.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/FunctionalTest.php
Minor bugfix that configures `Parameter#pattern` property instead of `Parameter#format`.
Tests provided that prove this implementation works as expected.
=> Fix #1239: FosRestDescriber properly configures Parameter#pattern property

ModelDescriber/Annotations/AnnotationsReader.php, ModelDescriber/Annotations/PropertyPhpDocReader.php, ModelDescriber/Annotations/SwgAnnotationsReader.php, ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, ModelDescriber/JMSModelDescriber.php, ModelDescriber/ObjectModelDescriber.php, Resources/doc/index.rst, SwaggerPhp/ModelRegister.php, Tests/Functional/Entity/JMSComplex.php, Tests/Functional/JMSFunctionalTest.php
That's quite weird to not be able to use ``@Model`` in objects, this PR fixes this limitation.
=> Support ``@Model`` in in-object annotations

Resources/views/SwaggerUi/index.html.twig
It can be confusing to have only "NelmioApiDocBundle" in the title bar when browing the doc.
I've added the title of the documentation so it's clearer.
=> Add the swagger spec info name in <title>

DependencyInjection/NelmioApiDocExtension.php, Describer/SwaggerPhpDescriber.php, Tests/Functional/Controller/ApiController.php
If an action use a LINK, UNLINK or COPY methods the bundle fails with: `Notice: Undefined index: link
in vendor/nelmio/api-doc-bundle/Describer/SwaggerPhpDescriber.php (line 174)`
OpenAPI doesn't supports the LINK and UNLINK methods so the bundle must ignore this methods.
Fix #1290
=> Ignore unsupported HTTP methods

ModelDescriber/FormModelDescriber.php, Tests/Functional/Form/DummyEmptyType.php, Tests/Functional/Form/UserType.php, Tests/Functional/FunctionalTest.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1184
Closes https://github.com/nelmio/NelmioApiDocBundle/pull/1224 (alternative implementation to it)
IMO this solution is better than #1224 because it does less "hacks" to infer the type, it just calls recursively itself solving the inner collection type. 
Since this PR just moves the code in a private method, suggest to have a look at a [split mode with no white spaces diff mode](https://github.com/nelmio/NelmioApiDocBundle/pull/1309/files?w=1) that should be much easier to review.
=> Handle form collection types

ModelDescriber/JMSModelDescriber.php, Tests/Functional/Entity/JMSUser.php, Tests/Functional/JMSFunctionalTest.php
|Bug fix?     |yes   |
|Fixed tickets|#1364 |
Solution based on @GuilhemN's suggestion (see https://github.com/nelmio/NelmioApiDocBundle/issues/1364#issuecomment-406713022).
**TODO:**
Closes #1364.
=> [JMSModelDescriber] Update `JMSModelDescriber` in order to iterate over nested array definitions

ModelDescriber/JMSModelDescriber.php, Tests/Functional/Controller/JMSController.php, Tests/Functional/Entity/JMSDualComplex.php, Tests/Functional/JMSFunctionalTest.php
jms/serializer default groups should not generate new definitions when possible.
This PR handles two cases
- When the default group is used
- When nested groups are used but on other properties that should not influence the current object
=> Jms serializer default groups should not generate new definitions when possible

ModelDescriber/FormModelDescriber.php, Tests/Functional/Form/DocumentType.php, Tests/Functional/Form/UserType.php, Tests/Functional/FunctionalTest.php
Adds support for the Doctrine MongoDB ODM `document` form type, which like `entity` extends `ChoiceType` and can be a multiple.
Also added test assertions for both `entity` and `document` with multiple enabled.
=> Added support for Doctrine MongoDB ODM 'document' form type

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, Tests/Functional/Controller/JMSController.php, Tests/Functional/Entity/JMSNamingStrategyConstraints.php, Tests/Functional/JMSFunctionalTest.php, Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php
Currenly `@NotNull` or `@NotBlank` constraints utilize reflection property name, which is incorrect for cases where naming strategy is involved.
=> [Bug] Respect property name for constraints

Describer/SwaggerPhpDescriber.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/FunctionalTest.php, Tests/Functional/TestKernel.php
We can define responses in configuration, but can't use it in while we describe schema.
=> Add ability to use response objects which defined in configuration

ModelDescriber/FormModelDescriber.php, Tests/Functional/Form/DummyType.php, Tests/Functional/FunctionalTest.php
This adds support for boolean enums. 
previous response was:
```php
[
'type' => 'string',
'enum' => [true, false],
]
```
The enum is in contradiction with the filed type. Now is:
```php
[
'type' => 'boolean',
'enum' => [true, false],
]
```
=> Add boolean enums support to forms

Model/ModelRegistry.php, ModelDescriber/JMSModelDescriber.php
As said in https://github.com/nelmio/NelmioApiDocBundle/pull/1311#issuecomment-423981494 ,  #1384 broke the jms nested group feature implemented with https://github.com/nelmio/NelmioApiDocBundle/pull/1311.
This PR re integrates it. To do so was necessary to allow to not auto-register aliases. This is mainly because of how the nested groups work, is fundamental to know which was the previous group.
This PR fixes also few issues in the merge commit https://github.com/nelmio/NelmioApiDocBundle/commit/63cee64e6b02ef6f3685ee4a568a81444936d2fe
I'm open to hear better proposal since `reserve_name` to me sounds as a workaround for disabling  https://github.com/nelmio/NelmioApiDocBundle/pull/1384, otherwise will be impossible to achieve this feature.
=> Restore jms nested groups feature

ModelDescriber/JMSModelDescriber.php, Tests/Functional/Controller/JMSController.php, Tests/Functional/Entity/JMSComplex.php
jms serializer group names are based on the internal property name, not on the serialized name
=> [bugfix] jms serializer group names are on property names

Resources/doc/customization.rst
"Just create a file..." was not OK (missing views/ subdirectory, wrong SwaggerUi case)
The path showcased as code-block's first row was OK
=> Fix NelmioApiDocBundle view customization instructions

Resources/doc/faq.rst
Here's how it's displayed [on symfony.com](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/faq.html#asset-files-not-loaded): the last word of the first line gets printed on the next row, while the two next lines have a nice indentation
:
After the fix, it will look like this:
No nice indentation under to emphasis the "A: " thing, but it looks a bit more readable
An alternative for that would be to ensure that the "or" doesn't get wrapped by fine-tuning on which word we wrap the line in the RST file, but it does not feel like the right thing to do
=> faq.rst: enhance readability in symfony.com docs

ModelDescriber/ObjectModelDescriber.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php
My models are described using interfaces, but when I tried to use "DateTimeInterface" wasn't working, only after change do DateTime or other custom DateTime format the documentation works.
The error:
```
The PropertyInfo component was not able to guess the type of DateTimeInterface::$timezone
```
=> Change validation to allow fields described as DateTimeInterface.

Describer/ApiPlatformDescriber.php, Resources/config/api_platform.xml, Tests/Describer/ApiPlatformDescriberTest.php
Fixes #1462
Adjust ApiPlatformDescriber to allow any implementation of NormalizerInterface that supports normalization of the ApiPlatform Documentation class.
Also added a unit test for the class.
=> Fix documentation decoration with API Platform

Form/Extension/DocumentationExtension.php
Add method that leads to deprecation message when missed:
> Not implementing the static getExtendedTypes() method in Nelmio\ApiDocBundle\Form\Extension\DocumentationExtension when implementing the Symfony\Component\Form\FormTypeExtensionInterface is deprecated since Symfony 4.2. The method will be added to the interface in 5.0.
Fixes #1448
=> Add implementation of FormTypeExtensionInterface::getExtendedTypes

.travis.yml, DependencyInjection/NelmioApiDocExtension.php, ModelDescriber/JMSModelDescriber.php, Tests/Functional/Controller/JMSController.php, Tests/Functional/Entity/BazingaUser.php, Tests/Functional/Entity/NestedGroup/JMSChatFriend.php, Tests/Functional/Entity/NestedGroup/JMSChatLivingRoom.php, Tests/Functional/Entity/NestedGroup/JMSChatRoom.php, Tests/Functional/Entity/NestedGroup/JMSChatRoomUser.php, Tests/Functional/JMSFunctionalTest.php, composer.json
This introduces support for  jms/serializer v2.0
It looks that because of dependencies, this will work only when both FOSRestBundle and BazingaHateoasBundle will support jms/serializer v2.0
Closes https://github.com/nelmio/NelmioApiDocBundle/issues/1464
Closes https://github.com/nelmio/NelmioApiDocBundle/issues/1437
=> Allow jms/serializer v2.0 and willdurand/Hateoas v3.0

Annotation/Areas.php, DependencyInjection/Configuration.php, DependencyInjection/NelmioApiDocExtension.php, Routing/FilteredRouteCollectionBuilder.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/Functional/Controller/ApiController.php, Tests/Routing/FilteredRouteCollectionBuilderTest.php, Util/ControllerReflector.php
Fix https://github.com/nelmio/NelmioApiDocBundle/issues/1246
A new boolean configuration is available in the areas: `with_annotation`.
By setting it to true, every route will be filtered by annotation.
Every route to match will need to add the `@Areas` with the area name.
the `default` area would only match the testAction(), while the `area2` will match both.
```yaml
areas:
default:
path_patterns:
- '^/api/'
with_annotation: true
area2:
with_annotation: true
```
```php
class ApiController
{
/**
* @Areas({'default', 'area2'})
*/
public function testAction()
{
}
/**
* @Areas({'area2'})
*/
public function test2Action()
{
}
}
```
=> add a way to filter areas on route by annotation

Resources/doc/alternative_names.rst
If it is used without `#/definitions/` the documentation gives an error: `Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath..`
=> Fix for missing basePath

UPGRADE-3.0.md
The generated "schema" did not follow the standard resulting in the following error: 
> Argument 1 passed to EXSyst\Component\Swagger\Schema::mergeExtensions() must be of the type array, string given
=> Fix schema in SwaggerDocblockConvertCommand

Controller/DocumentationController.php, Tests/Functional/FunctionalTest.php, Tests/Functional/SwaggerUiTest.php
In our scenario we can have multiples `urls` leading to the same project, and in the docs we can only provide one host to the complete documentation. To swagger ui it's not problem because the javascript if the `host` it's not provided, the `window.location` is used instead. So this pr is just to add the same behaviour to the .json generation. 
Another idea is provide a configuration to say something like `auto_discover_host`.
What do you think about it?
about build:
I don't from where this error is coming from.
=> Provide default host to generated .json documentation

DependencyInjection/NelmioApiDocExtension.php, ModelDescriber/FallbackObjectModelDescriber.php, ModelDescriber/JMSModelDescriber.php, ModelDescriber/ObjectModelDescriber.php, Resources/config/services.xml, Tests/Functional/Entity/JMSUser.php, Tests/Functional/JMSFunctionalTest.php, Tests/Functional/ModelDescriber/VirtualTypeClassDoesNotExistsHandlerDefinedDescriber.php, Tests/Functional/TestKernel.php
Currently is not possible to describe at all custom jms type handlers (they are pretty common in complex apis). This change allows to describe via custom describers jms virtual types.
The change in behavior from the current status is substantial.
The current implementation will just not define the type for a property, while with this change sill throw an exception saying something as "Schema of type "...." can't be generated, no describer supports it".
This obliges the user to have all the types defined. Not sure if it is the best approach.
Solution used here is to add a fallback describer, defined for all the types, that just does nothing and emulates the current behavior.
The only drawback from this solution is that will create empty types jms virtual types... that could be a not bad …
=> Allow model describers on jms custom types

.travis.yml, ModelDescriber/JMSModelDescriber.php, Tests/Functional/Entity/NestedGroup/JMSChatFriend.php, Tests/Functional/Entity/NestedGroup/JMSChatUser.php, Tests/Functional/JMSFunctionalTest.php, Tests/Functional/SwaggerUiTest.php, Tests/Functional/TestKernel.php, composer.json
This PR moves outside of NelmioApiDocBundle the logic for groups detection.
In this way jms/serializer can change the groups logic without affection NelmioApiDocBundle code.
Another advantage or this solution is that will be possible to introduce easily other exclusion strategies (as versioning) without changing too much code.
TODO:
=> Use jms/serializer groups detection logic

ModelDescriber/BazingaHateoasModelDescriber.php, ModelDescriber/JMSModelDescriber.php, Tests/Functional/BazingaFunctionalTest.php, Tests/Functional/Controller/BazingaTypedController.php, Tests/Functional/Entity/BazingaUser.php, Tests/Functional/EntityExcluded/BazingaUserTyped.php, Tests/Functional/SwaggerUiTest.php, Tests/Functional/TestKernel.php, composer.json
This "documents" the type on an embedded relation in hateoas 3.0
Previously the embedded relations were just simple `object` types.
As of hateoas 3.0 is possible to declare via metadata the type of an embedded relation, so that type can be used in the api doc.
=> Support typed embedded relation with willdurand/hateoas 3.0

Resources/public/init-swagger-ui.js
Currently user has to provide authorization every time page is refreshed. During development this becomes extremely annoying as after every change you need to refresh the page and thus re-authorize.
This PR hooks into the swagger authorization mechanism to store the authorization in local storage and restore it on page reload (essentially providing the behavior of API Key storage like it was in V2)
=> Cache authorization in local storage.

.travis.yml, DependencyInjection/Configuration.php, Formatter/HtmlFormatter.php, Resources/config/formatters.xml, Resources/doc/configuration-reference.rst, Resources/views/method.html.twig, Resources/views/resource.html.twig, Resources/views/resources.html.twig, Tests/Formatter/testFormat-result-no-dunglas.markdown, Tests/Formatter/testFormat-result.markdown
The `templating` service has been deprecated.
It needs to be replaced by `twig`.
Since `TwigEnvironment` is used, it needs the namespaced paths (the old syntax is not supported anymore).
This is blocking for API Platform.
I fixed at least one test suite in Travis.
=> Compatibility with Symfony 4.3

Tests/Describer/RouteDescriberTest.php, Tests/Functional/BazingaFunctionalTest.php, Tests/Functional/FunctionalTest.php, Tests/Functional/JMSFunctionalTest.php, Tests/Functional/SwaggerUiTest.php, Tests/Functional/WebTestCase.php, Tests/Routing/FilteredRouteCollectionBuilderTest.php
FOSRestBundle prevents installing some symfony components in version 5 as it is not compatible yet. I removed the dev requirement locally on FOSRestBundle and got a few incompatibility issues.
-  `Booting the kernel before calling %s() is not supported, the kernel should only be booted once.` on some functional tests
- removed/missing `Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser`-class
=> fix compatibility with symfony 5

composer.json
There are no breaking changes at [phpdocumentor/reflection-docblock v5.0.0](https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.0.0).
=> Allow "phpdocumentor/reflection-docblock:5.0"

ModelDescriber/Annotations/PropertyPhpDocReader.php
Solved this error on last update (3.6.0) due to InvalidTag which doesn't has description method
```
[2020-03-05 11:24:55] php.CRITICAL: Uncaught Error: Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\InvalidTag::getDescription() {"exception":"[object] (Error(code: 0): Call to undefined method phpDocumentor\\Reflection\\DocBlock\\Tags\\InvalidTag::getDescription() at /home/wwwroot/capsule_back/vendor/nelmio/api-doc-bundle/ModelDescriber/Annotations/PropertyPhpDocReader.php:48)"} []
[2020-03-05 11:24:55] app.ERROR: {"code":0,"message":"Attempted to call an undefined method named \"getDescription\" of class \"phpDocumentor\\Reflection\\DocBlock\\Tags\\InvalidTag\".","called":{"file":"\/home\/wwwroot\/capsule_back\/vendor\/nelmio\/api-doc-bundle\/ModelDescriber\/Annotations\/An …
```
=> Fix invalid tag which doesn't has description

Describer/SwaggerPhpDescriber.php
I faced a problem when turned on opcache.preloader with Symfony 5.0: PHP failed with error about Anonymous class which extends non-preloaded `SWG\Swagger` class.
=> Help opcache.preload to load Swagger annotation class

ModelDescriber/JMSModelDescriber.php, Tests/Functional/Entity/JMSNote.php, Tests/Functional/Entity/JMSUser.php, Tests/Functional/JMSFunctionalTest.php
https://jmsyst.com/libs/serializer/master/reference/annotations#inline
When this feature is used, properties are declare in the parent class
=> Add support for JMS Serializer inline property feature

RouteDescriber/RouteMetadataDescriber.php, Tests/RouteDescriber/RouteMetadataDescriberTest.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1628#issuecomment-636150293 and https://github.com/nelmio/NelmioApiDocBundle/pull/1623#issuecomment-635522664
=> Fix access to api->components in RouteMetadataDescriber

ModelDescriber/Annotations/AnnotationsReader.php, Tests/Functional/Entity/JMSUser.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php, Tests/Functional/JMSFunctionalTest.php
Fix for #1623
Phpdoc reader update property checks for title and if blank updates the property.
This should therefore run after the OA3 Annotations processing of title.
=> Fix User Warning: Multiple definitions for @OA\\Property()->title

Command/DumpCommand.php, Resources/config/services.xml, Tests/Command/DumpCommandTest.php
Command outputs to stdout, so can be redirected to a file.
Pretty prints output by default.
--no-pretty can be passed to remove whitespace from json output if it does not need to be human readable
=> Add dump command to print out swagger JSON. (#1537)

Model/ModelRegistry.php, ModelDescriber/ObjectModelDescriber.php, PropertyDescriber/ArrayPropertyDescriber.php, PropertyDescriber/BooleanPropertyDescriber.php, PropertyDescriber/CompoundPropertyDescriber.php, PropertyDescriber/DateTimePropertyDescriber.php, PropertyDescriber/FloatPropertyDescriber.php, PropertyDescriber/IntegerPropertyDescriber.php, PropertyDescriber/NullablePropertyTrait.php, PropertyDescriber/ObjectPropertyDescriber.php, PropertyDescriber/PropertyDescriberInterface.php, PropertyDescriber/StringPropertyDescriber.php, Resources/config/services.xml, Tests/Functional/Controller/ApiController.php, Tests/Functional/Entity/CompoundEntity.php, Tests/Functional/FunctionalTest.php, UPGRADE-4.0.md
This PR adds support for Compound types like: `@var Object1|Object2` in Object properties.
It leverages OA3 `oneOf` polymophism feature
=> Add support for compound properties

ModelDescriber/Annotations/AnnotationsReader.php, ModelDescriber/Annotations/PropertyPhpDocReader.php, ModelDescriber/Annotations/SwgAnnotationsReader.php, ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, ModelDescriber/ObjectModelDescriber.php, Tests/Functional/Entity/SymfonyConstraints.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php
Add support for things like:
```php
class Foo  {
/**
* @SWG\Property(property="bar", example=2)
*/
private $id;
/**
* @SWG\Property(description="bla")
*/
function getId() { ... }
}
=> Add methods metadata support for models

ApiDocGenerator.php, OpenApiPhp/DefaultOperationId.php, Tests/Functional/FunctionalTest.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1676 by disabling the OperationId from zircote/swagger-php (see https://github.com/zircote/swagger-php/blob/91bfae956a5db9f777f5cd091f46c900928fc5e0/src/Processors/OperationId.php).
It's been enabled by default in swagger-php 3.x but it is not working well with the custom contexts we use, so I think it's better to shortcut this processor.
=> Disable the OperationId processor

PropertyDescriber/ArrayPropertyDescriber.php, Tests/Functional/Entity/User.php, Tests/Functional/FunctionalTest.php
This PR fixes nullable array property descriptions:
```
/**
* @var Class[]|null
*/
$property;
```
will be now described also with nullable flag in OA specs.
=> Fix nullable array properties

Util/ControllerReflector.php
PR for issue #1698
By default, the PHP configuration routes return an array with the controller name and method, since the reflection class was typed for string only this was causing an exception when the user was not using YAML or XML configuration.
This change removes the string type hint from the method and checks if it's an array or string to do the reflection.
=> Supports reflection for routes configured in PHP files.

RouteDescriber/FosRestDescriber.php, Tests/Functional/FOSRestTest.php
Hello, 
i came across this incorrect backslash in `application\json` media type, when i was using FOSRest @ReqeustParam annotation to define request body.
=> Fix incorrect media types in FosRestDescriber

RouteDescriber/RouteDescriberTrait.php
Fix #1673
Looking at the discussion of the issue, this was the proposed fix.
=> Remove the @internal tag to avoid deprecations on symfony 5.1 (#1673)

Controller/SwaggerUiController.php, Tests/Functional/SwaggerUiTest.php
`swagger-ui-bundle` is very sensible to encoding changes because of the
RegExp performed.
ensuring UTF-8 on the response prevents end-user config to break it.
the annotations already needs to be UTF-8 compatible to generate the
JSON, so it should not break users applications.
when i was improving the tests to check the charset i saw that it was already tested using the `content-type` header, but using symfony 3.4.44 with the version 3.7.4 of this bundle the `getCharset` was returning `null`
(i dont know if i should open for this branch... but seemed the better option)
=> (feat): add utf-8 charset to response

Resources/doc/customization.rst, Resources/public/init-swagger-ui.js, Resources/views/SwaggerUi/index.html.twig
Hi,
Related to #1330 and and #1662
Instead of having to rewrite the whole `init-swagger-ui.js`, this allows to use template overriding with like this:
```
{% extends "@!NelmioApiDoc/SwaggerUi/index.html.twig" %}
{% block swagger_initialization %}
<script type="text/javascript">
window.onload = loadSwaggerUI({
defaultModelsExpandDepth: -1,
deepLinking: true,
});
</script>
{% endblock %}
```
It might be a BC break (but maybe we can find a way around it).
=> Allow to pass options to the constructor of SwaggerUIBundle

RouteDescriber/FosRestDescriber.php
I was facing some errors using our swagger in json because of `collectionFormat` with `multi` value is invalid since it's part of Open Api 2 spec.
It comes from `@Rest\QueryParam` with map option which generate this.
=> Fix Fos rest query param with map

DependencyInjection/Compiler/ConfigurationPass.php, ModelDescriber/FormModelDescriber.php, Tests/Functional/Form/UserType.php, Tests/Functional/FunctionalTest.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1748
=> Allow the usage of `@SWG\Definition` on form types

Annotation/Security.php, Describer/OpenApiPhpDescriber.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/FunctionalTest.php
This PR aims at supporting a value in Security annotation, to follow [OpenApi specification](https://swagger.io/specification/#patterned-fields-3).
=> Support oauth2 scopes in Security annotation

ModelDescriber/ApplyOpenApiDiscriminatorTrait.php, ModelDescriber/ObjectModelDescriber.php, Tests/Functional/Controller/ApiController.php, Tests/Functional/Entity/SymfonyDiscriminator.php, Tests/Functional/Entity/SymfonyDiscriminatorOne.php, Tests/Functional/Entity/SymfonyDiscriminatorTwo.php, Tests/Functional/FunctionalTest.php, Tests/ModelDescriber/ApplyOpenApiDiscriminatorTraitTest.php
This should close https://github.com/nelmio/NelmioApiDocBundle/issues/1610
Relevent OpenAPI Docs: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/
Big caveat here is that I also tried to add support for this with the JMS Serializer and hit an issue that seems to be a blocker:
- https://github.com/schmittjoh/JMSSerializerBundle/issues/292
- https://github.com/schmittjoh/JMSSerializerBundle/issues/299
It seems like the discriminator field in JMS is "virtual" and isn't actually included in serialized outputs. There's probably a way around this with serialization groups, but I'm not familiar enough with JMS serializer to make itwwork and make a test that would really test what's going on. The work here should support adding support for polymorphism stuff to JMS …
=> Support Polymorphism via the Symfony Discriminator Map

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php
Should fix https://github.com/nelmio/NelmioApiDocBundle/issues/1780
Sometimes folks will set a `min` length without a max, for instance and
the generated open api schema would previously have been nonsense:
```
"property": {
"type":"string",
"maxLength":0,
"minLength":1
}
```
=> Check Min and Max in Length Constraints Before Setting in Schemas

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, Tests/Functional/Entity/SymfonyConstraints.php, Tests/Functional/FunctionalTest.php, Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php
Should fix https://github.com/nelmio/NelmioApiDocBundle/issues/1783 (sick of me yet?! 🙃 )
Otherwise JSON schema like this is generated:
```
"property": {
"type": "array",
"enum": ["one", "two", "three"],
"items": {
"type": "string"
}
}
```
With this change, however, this schema is generated:
```
"property": {
"type": "array",
"items": {
"type": "string",
"enum": ["one", "two", "three"]
}
}
```
A possible downside here is that the symfony constraint stuff happens
before types are figured out from PHPDoc. So it's _possible_ to end up
with something that won't validated. Take something like this:
```
/**
* @Assert\Choice(multiple=true, choices={"..."})
* @var string
*/
```
This would generate:
```
"property": {
"type": "string",
"items": {
"enum": ["..."]
}
}
```
=> Apply `enum` from Choice Constraints to Items When Choice is Multiple

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php
Since Symfony 5.2, it is possible to annotate constraints using PHP 8.0 attributes. When I turn a constraint annotation into an attribute however, it becomes invisible to NelmioApiDocBundle. With this PR, I'd like to fix this problem.
=> Added support for constraint attributes

Routing/FilteredRouteCollectionBuilder.php, Tests/Routing/FilteredRouteCollectionBuilderTest.php
This issue was introduced in #1556.
=> Fix calls to nonexistent method `ControllerReflector::getReflectionClassAndMethod()`

Resources/doc/index.rst
This PR fixes some minor issues in this RST doc. The main issue was the use of `<0xa0>` instead of normal white spaces. My text editor showed it like this:
=> [Doc] Some minor fixes in index.rst

RouteDescriber/FosRestDescriber.php, Tests/Functional/Controller/FOSRestController.php, Tests/Functional/FOSRestTest.php
When using the following requierement:
```
@Rest\QueryParam(name="updatedFrom", strict=true, nullable=true, requirements=@Constraints\DateTime("Y-m-d\TH:i:s"))
```
According to the OpenAPI 3.0 documentation https://swagger.io/specification/, 
We should have ``"format": "date-time"`` rather than ``"format": "DateTime"`` in the generated doc
=> Fix Open API doc for DateTime requirements

DependencyInjection/NelmioApiDocExtension.php
I've upgraded an application that uses this bundle to Symfony 5.3, which resulted in the following error:
```
The definition for "nelmio_api_doc.generator_locator" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.
```
Symfony's [documentation on service locators](https://symfony.com/doc/4.4/service_container/service_subscribers_locators.html#reusing-a-service-locator-in-multiple-services) uses a dedicated class, but `NelmioApiDocExtension` doesn't.
I've fixed the error by adding the documented class to the service definition.
Fixes #1807
=> Added a class to the nelmio_api_doc.generator_locator service definition

composer.json
Follows #1790.
This library is able to consume implementations of `psr/cache` versions 2 and 3 as well, so it should not block their installation.
=> Allow psr/cache versions 2 and 3

Resources/doc/areas.rst
Add an extra `name_patterns` example to areas docs
=> Add extra `name_patterns` example to areas docs

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, Tests/ModelDescriber/Annotations/SymfonyConstraintAnnotationReaderTest.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1822
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1821
This is pretty much identical to previous PR I sent to fix the `Count` constraint https://github.com/nelmio/NelmioApiDocBundle/pull/1781
=> Fix Count and Range Constraints

Resources/doc/index.rst
When using serializer context groups in JMS serializer, even if just using the Default group in one place explicitly and leaving it blank in another, they will be treated as different component schemas, even though to the serializer outcome they are the same.
Documenting behavior of decision with side effect.
=> Updates documentation to show a side effect of design decision regarding context groups with JMS serializer

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
*Context*: NelmioApiDocBundle does not require clients to have the symfony/validator package. However it requires it in its dev dependencies.
*Problem*: If client of library does not have symfony/validator and uses PHP8, NelmioApiDocBundle will assume that symfony/validator is installed, in `SymfonyConstraintAnnotationReader.php`
*Solution*: We should not assume that client has symfony/validator. So before reading attributes of this class, we now try to see if class exists. 
- Tests still run.
- Tested in a project without symfony/validator and requiring this version, it now works.
The error before this fix was : 
Exception: `ClassNotFound`
Message for me: `Attempted to load class "Constraint" from namespace "Symfony\Component\Validator".
Did you forget a "use" statement for e.g. …
=> Add a check for Constraint class existing before using it

Resources/doc/index.rst
The real issue is the lack of `php` in the second `.. code-block::`.
The blank line added after the first `.. code-block::` is to keep it consistent with the rest of code blocks.
=> [Doc] Fix some minor RST issues

ModelDescriber/FormModelDescriber.php
The form describer wasn't showing description and title for non native form type childs.
I'm really not an OpenApi expert, there is probably a better way to fix that.
Before
After
I didn't see any tests related to the form describer, do I need to add some ?
=> Display non native form type childs description and title properly

Tests/Functional/Entity/JMSUser.php, Tests/Functional/JMSFunctionalTest.php, Tests/Functional/TestKernel.php, Tests/Functional/WebTestCase.php
This PR improves the tests checking that no "automatic" names are generated if all the other params (as aliases) are well defined
=> Improve jms testing by checking that collisions are not generated

ApiDocGenerator.php, ModelDescriber/Annotations/OpenApiAnnotationsReader.php, OpenApiPhp/ModelRegister.php
Upcoming changes in swagger-php will make `context` a required parameter for instantiating `Analysis` and when adding annotations to the created `Analysis` instance.
See https://github.com/zircote/swagger-php/pull/963 for more details.
=> Always provide a context to swagger-php

DependencyInjection/Configuration.php, DependencyInjection/NelmioApiDocExtension.php, Resources/doc/faq.rst, Routing/FilteredRouteCollectionBuilder.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/Routing/FilteredRouteCollectionBuilderTest.php
By adding a  new config parameter it is possible to hide the "default" section in your config.
Approach is to not register the RouteDescriber as a tagged service per area.
Fixes: https://github.com/nelmio/NelmioApiDocBundle/issues/1458
=> [3.x]: Hide the default section per area with new config parameter

Resources/doc/customization.rst
This doc page advises that one can `have a look at the original template to see which blocks can be overridden`, but does not say where the original template can be found.  This edit adds that information for clarity.
Note that I haven't run any tests as this is a docs-only change.
=> Add Location of Original Template

Render/Html/GetNelmioAsset.php
Symfony 5.4 returning deprecations about 
```
User Deprecated: Method "Twig\Extension\ExtensionInterface::getFunctions()" might add "array" as a native return type declaration in the future.
Do the same in implementation "Nelmio\ApiDocBundle\Render\Html\GetNelmioAsset" now to avoid errors or add an explicit @return annotation to suppress this message.
```
Closes #1921
=> fixed : add doc blocks to silence Symfony deprecations

DependencyInjection/NelmioApiDocExtension.php
fix #1876
it will work at least from symfony 4.4 https://github.com/symfony/twig-bundle/blob/4.4/DependencyInjection/Compiler/ExtensionPass.php#L28 to symfony 6.0 https://github.com/symfony/twig-bundle/blob/6.0/DependencyInjection/Compiler/ExtensionPass.php#L30
=> disable html render if `symfony/asset` not installed

Resources/doc/customization.rst, Resources/views/SwaggerUi/index.html.twig
In attempting to remove the default green header from the API docs (I am integrating the docs into a site that already has a header), I have found that the only possible way to do so is to overwrite the entire ``index.html.twig`` file.  This is because the existing ``{% header %}`` twig tags are placed *inside* the ``<header>`` HTML tags.  So, if one overrides the ``{% header %}`` block, it only adjusts the header content, as opposed to allowing control over the entire header object.
To resolve this problem I considered two methods:
- Move the existing ``{% header %}`` tags _*outside*_ of the ``<header>`` tags.  This would resolve the problem in the simplest fashion, but would be a breaking change for those currently overriding the block.
- Add a new twig block, placing its tags …
=> Proposal: Add ``header_block`` Twig Block

Tests/Util/ControllerReflectorTest.php, Util/ControllerReflector.php
=> Add missing null check to ControllerReflector::getReflectionMethod

.github/workflows/continuous-integration.yml
Currently, the CI runs 6 checks, some of them being unnecessary:
* PHP 7.2 / lowest deps
* PHP 7.2 / Symfony 4.0
* PHP 7.3 / Symfony 5.0
* PHP 7.4 / Symfony 4.0
* PHP 7.3 / Symfony 5.0
* PHP 8.0 / highest deps
I propose to add PHP 8.1 and simplify the matrix, while testing supported Symfony minors as well:
* PHP 7.2 / lowest deps (covers Symfony 4.0)
* PHP 7.3 / Symfony 4.4
* PHP 7.4 / Symfony 5.3 (still maintained until Jan 2022)
* PHP 8.0 / Symfony 5.4
* PHP 8.1 / Symfony 5.4 (equivalent of highest deps, the default behavior of Composer)
This decrease the amount of CI builds done while testing more dependencies cases.
=> Add PHP 8.1 in CI and better test supported Symfony minors

ModelDescriber/ObjectModelDescriber.php
Fixes #1937 
I've tested locally but maybe we should have a functional test with symfony serializer not installed?
=> Fixes symfony serializer being mandatory

Describer/OpenApiPhpDescriber.php, Resources/doc/index.rst, Resources/doc/security.rst, Tests/Functional/Controller/ApiController80.php, Tests/Functional/Controller/ApiController81.php, Tests/Functional/FunctionalTest.php
When using the bundle and including global bundle security information using `package/nelmio_api_doc.yaml` as per the [Symfony documentation](https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#using-the-bundle), it becomes impossible to override this security policy.
Instead of having to remove this global security and configure each route individually using the `@Security` annotation. It is much less repetitive to be able to remove all existing security policies for a specific route using this annotation.
Changes:
If the Security annotation is used on a route and the name is set to `null`, all security policies for that route will be removed.
Created documentation for using the `@Security` annotation
=> Allow global security policies to be removed

Annotation/Areas.php
the documentation shows this usage:
```
#[Areas(['area1', 'area2'])]
```
but it was actually working like this:
```
#[Areas(['value' => ['area1', 'area2']])]
```
=> Fixed Areas attribute to work like the documentation specifies

ModelDescriber/EnumModelDescriber.php, Resources/config/services.xml, Tests/Functional/Controller/ApiController81.php, Tests/Functional/Entity/Article81.php, Tests/Functional/Entity/ArticleType81.php, Tests/Functional/FunctionalTest.php, composer.json
I have not written any test, but it works fine for my usage : a simple enum used as a choice list in a property of an object.
ref #1963
=> Create an enum model describer

ModelDescriber/Annotations/AnnotationsReader.php, ModelDescriber/Annotations/UpdateClassDefinitionResult.php, ModelDescriber/FormModelDescriber.php, ModelDescriber/JMSModelDescriber.php, ModelDescriber/ObjectModelDescriber.php, Resources/doc/faq.rst, Tests/Functional/Controller/ApiController80.php, Tests/Functional/Entity/EntityWithAlternateType.php, Tests/Functional/Entity/EntityWithObjectType.php, Tests/Functional/Entity/EntityWithRef.php, Tests/Functional/Form/FormWithAlternateSchemaType.php, Tests/Functional/Form/FormWithRefType.php, Tests/Functional/FunctionalTest.php
This basicaly let's user do this:
```php
/**
* @OA\Schema(type="array", https://github.com/OA\Items(ref=@model(type=SomeEntity::class)))
*/
class SomeCollection implements \IteratorAggregate { }
```
on a plain PHP object or form and the model describers (object, JMS, and form) will stop and _not_ try to describe any further properties.
This should close https://github.com/nelmio/NelmioApiDocBundle/issues/1957 as well as quite a few other issues since this has come up a lot.
Right now if an `object` type in a schema will still describe properties. Should we completely short circuit if _any_ type is defined? Assume the user has manually defined everything?
=> Stop Model Property Description When a Schema Type or Ref is Already Defined

ApiDocGenerator.php, Model/ModelRegistry.php, ModelDescriber/Annotations/OpenApiAnnotationsReader.php, ModelDescriber/ApplyOpenApiDiscriminatorTrait.php, ModelDescriber/FormModelDescriber.php, ModelDescriber/JMSModelDescriber.php, OpenApiPhp/ModelRegister.php, OpenApiPhp/Util.php, PropertyDescriber/ObjectPropertyDescriber.php, RouteDescriber/FosRestDescriber.php, Tests/Functional/SwaggerPHPApiComplianceTest.php, Tests/SwaggerPhp/UtilTest.php
Fixes https://github.com/nelmio/NelmioApiDocBundle/issues/1984
Currently, in some places new Swagger-php annotations do not have a parent context, and thus do not inherit from the root context.
This causes issues with the new version field which uses the context extensively.
This PR fixes this and uses the same root context everywhere.
=> Use the same root context everywhere

Controller/SwaggerUiController.php
My case, while I dev, I got an error on Swagger UI without explicite details about why it bugged.
With previous exception set on line 51, it improve debug by providing the original exception.
=> Add previous exception to BadRequestHttpException on SwaggerUiController

Resources/doc/index.rst
I suppose it means that routes under `/api/doc` will not be parsed for api documentation.
=> Fix typo "expect" to "except" in documentation.

.github/workflows/continuous-integration.yml
Recent composer version requires to allow plugin before execution.
=> Allow symfony/flex composer plugin in CI

DependencyInjection/NelmioApiDocExtension.php
It helps user to define their own model describer by adding the tag automatically.
=> Add autoconfigure for model describer tag

ModelDescriber/ObjectModelDescriber.php, Tests/Functional/Controller/ApiController80.php, Tests/Functional/Entity/ArticleInterface.php
I've encountered a class hierarchy where there was an interface.
The ObjectModelDescriber already behave well with interface but the `class_exists` prevent it from being used with interface.
Not sure if I'm missing something.
=> The ObjectModelDescriber can support interfaces

DependencyInjection/NelmioApiDocExtension.php, ModelDescriber/ObjectModelDescriber.php, Resources/config/services.xml, Tests/Functional/Controller/ApiController80.php, Tests/Functional/Entity/SymfonyDiscriminatorFileMapping.php, Tests/Functional/Entity/SymfonyDiscriminatorOne.php, Tests/Functional/Entity/SymfonyDiscriminatorTwo.php, Tests/Functional/FunctionalTest.php, Tests/Functional/Resources/serializer/discriminator.yaml, Tests/Functional/TestKernel.php
Currently, the bundle can extract discriminator mappings only from the annotations. This MR uses Serializer's metadata factory to support all of configurations: annotations, yaml files, etc.
=> Read discriminator mapping from file configuration

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
Currently ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php not display constraints when use Assert\Sequentially, it should works like Assert\Compound
=> Adding support for Symofny Assert\Sequentially

OpenApiPhp/ModelRegister.php
Simple fix to reference class correctly, fixing XML API descriptions.
=> Fix OA\XmlContent class reference

ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, Tests/Functional/Entity/SymfonyConstraintsWithValidationGroups.php, Tests/Functional/ValidationGroupsFunctionalTest.php
Steps to reproduce:
- enable `use_validation_groups: true` in configuration
- add model property with type `array` and `Assert\Valid` constraint on it
- try to build Api Doc
Got `array_intersect(): Argument #2 must be of type array, null given` in the `ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php:228`
=> Fix type error in SymfonyConstraintAnnotationReader

ModelDescriber/JMSModelDescriber.php
if a type is hinted as `DateTimeInterface`, the API doc wont work well as `is_subclass_of('DateTimeInterface', 'DateTimeInterface')` returns false
=> Ensure date time interface is described as expected

Resources/doc/index.rst
Putting thumbs down on messages is not constructive, but submitting a PR is.
- Resolves #1220
=> add tip to install twig and assets packages.

PropertyDescriber/NullablePropertyTrait.php, Tests/Functional/Controller/ApiController80.php, Tests/Functional/Entity/EntityWithNullableSchemaSet.php, Tests/Functional/FunctionalTest.php
My use case is I have an entity which has a nullable string `?string` property (so the deserialization will work, since `null` can be passed) but the validation will check that it is not null, in which case I know that it will always be a `string`
Without this change, even tough I have `@OA\Property(nullable=false)` set in the entity, it gets ignored... this change fixes this and it will show up correctly as `nullable: false` in swagger docs
Made a small change after the fact, it checks if `nullable` is not undefined, and if it's false it will mark it undefined, so they don't show up as `nullable: false` for all the properties in the doc which is not necessary
=> Check nullable property has nullable set

RouteDescriber/RouteMetadataDescriber.php, Tests/RouteDescriber/RouteMetadataDescriberTest.php
Adds an "enum" schema to route parameters if the routing requirements consists only of a simple OR regex epression.
It skips complex expression.
The schema "pattern" field still contains the original regex.
This is mainly useful to display enum values in the Swagger UI gui as select boxes rather than text boxes.
=> Add enum description to route parameter if possible.

DependencyInjection/Compiler/PhpDocExtractorPass.php, NelmioApiDocBundle.php
I found that `property_info.php_doc_extractor` won't be available at Symfony ^5.0, if NelmioApiDocBundle is required for dev only.
https://github.com/symfony/symfony/blob/6.1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1889
That's why I added custom pass for this class. Since `reflection-docblock` is mandatory, there is no need to check for `ContainerBuilder::willBeAvailable`.
=> Fix `phpdocumentor/reflection-docblock` usage for `dev`

ModelDescriber/SelfDescribingModelDescriber.php, ModelDescriber/SelfDescribingModelInterface.php, Resources/config/services.xml, Tests/ModelDescriber/Fixtures/SelfDescribingModel.php, Tests/ModelDescriber/SelfDescribingModelDescriberTest.php
This PR implements self-describing models: models that are able to describe their structure through a static method call.
I already use this technique in one of my projects with league/fractal (https://fractal.thephpleague.com): in Fractal, there is a concept of Transformers, classes that are able to transform a given object into an array. These transformers can be nested and used in collections.
Such transformers carry the output structure of my API: they are dedicated classes that I wish I could use as "models". They do not however match the currently available models describers. Thus I'd like to propose self-describing models: the ability for model classes to implement an interface and describe their structure in a static method:
```php
class SelfDescribingModel implements …
```
=> Add self-describing model describer

Tests/Functional/FunctionalTest.php
Since zircote/swagger-php [4.5.5](https://github.com/zircote/swagger-php/releases/tag/4.5.5) the Attribute `OpenApi\Attributes\PathParameter` no longer extends `OpenApi\Annotations\PathParameter`, which broke the testcase that is being modified in this PR.
It is also possible to just assert if it is an instance of `OpenApi\Generator\Parameter`, but I personally I prefer to keep it as specific as it is right now.
I'm not a big fan of the aliases I made, so I'm happy if there are better suggestions. On the other hand, this is pretty clear now.
=> Fixes assertion in test to make it compatible with zircote/swagger-php >=4.5.5

Resources/doc/security.rst
A missing ``-`` prevents the default security policy from being set.
Added attributes/annotations switcher to the configuration block.
=> Fixed minor error in the default security policy documentation.

Command/DumpCommand.php, NelmioApiDocBundle.php
Fixes next deprecations errors for new symfony 6.3.
bin/console lint:container
{"message":"User Deprecated: Method \"Symfony\\Component\\HttpKernel\\Bundle\\Bundle::build()\" might add \"void\" as a native return type declaration in the future. Do the same in child class \"Nelmio\\ApiDocBundle\\NelmioApiDocBundle\" now to avoid errors or add an explicit @return annotation to suppress this message.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Method \"Symfony\\Component\\HttpKernel\\Bundle\\Bundle::build()\" might add \"void\" as a native return type declaration in the future. Do the same in child class \"Nelmio\\ApiDocBundle\\NelmioApiDocBundle\" now to avoid errors or add an explicit @return annotation to suppress this …
=> Deprecations fixes for symfony 6.3

Tests/ModelDescriber/ApplyOpenApiDiscriminatorTraitTest.php, Tests/Render/RenderOpenApiTest.php, composer.json, phpunit-baseline.json, phpunit.xml.dist
Changes:
- `api-platform/core` dependency now uses `"^2.7.0|^3"` instead of `"^2.7.0|^3@dev"` (Fixes all functional tests failing)
- Update `symfony/phpunit-bridge` dependency from `"^5.4.23"` to `"^6.3.2"` ([Baseline deprecations](https://symfony.com/doc/current/components/phpunit_bridge.html#baseline-deprecations))
- Generate baseline for unfixable `Nelmio\\ApiDocBundle\\Tests\\Functional\\SwaggerUiTest` api-platform self-deprecations
=> Fix failing phpunit

ModelDescriber/FormModelDescriber.php, ModelDescriber/JMSModelDescriber.php, PropertyDescriber/ObjectPropertyDescriber.php, Tests/Functional/FunctionalTest.php, Tests/Functional/JMSFunctionalTest.php
Fix when generating a nullable property (an enum for example) in OpenApi 3.1.0.
swagger-php makes sure that the `nullable` property is unset when working with OpenApi 3.1.0 and transform it to the 3.1.0 equivelant (see: https://github.com/zircote/swagger-php/blob/595d8b63a589e6ac0835c83a45304c7397dc37d1/src/Annotations/AbstractAnnotation.php#L390-L402), but this doesn't work when using `allOf`.
This PR aims to fix that by replacing `allOf` with `oneOf`. Additionally `oneOf` is more logical to use in this context than `allOf`  since `allOf` means that every schema could be valid where `oneOf` means that only one schema can be valid https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/.
=> fix: use oneOf instead of allOf

ModelDescriber/JMSModelDescriber.php, Tests/Functional/Controller/JMSController81.php, Tests/Functional/JMSFunctionalTest.php, Tests/Functional/TestKernel.php, phpunit-baseline.json
`jms/serializer` introduced enum support since [v3.20](https://github.com/schmittjoh/serializer/releases/tag/3.20.0) and added a new type: https://github.com/schmittjoh/serializer/blob/402a12629e3ad6d6897273769808a28c32745309/src/Metadata/Driver/EnumPropertiesDriver.php#L50
And since `jms/serializer-bundle` [v5.2.1](https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/5.2.1) and https://github.com/schmittjoh/JMSSerializerBundle/pull/919 with `jms_serializer.enum_support: true` all existing models with enums got broken, because now enum properties are referenced to the fixed string `#/components/schemas/enum` instead of the correct `#/components/schemas/EnumClassName`:
```json
{
"openapi": "3.0.0",
"info": {},
"paths": {
"/api/card/random": {
"get": {
"operationId": …
```
=> Add jms/serializer enum support

RouteDescriber/RouteArgumentDescriber/SymfonyMapQueryStringDescriber.php, RouteDescriber/RouteArgumentDescriber/SymfonyMapRequestPayloadDescriber.php, Tests/Functional/Controller/ApiController81.php, Tests/Functional/SymfonyFunctionalTest.php, phpunit-baseline.json
fixes https://github.com/nelmio/NelmioApiDocBundle/pull/2112#issuecomment-1892411364
=> fix: attribute validation groups not passed

src/PropertyDescriber/ObjectPropertyDescriber.php, tests/Functional/Fixtures/Controller2209.json, tests/Functional/Fixtures/MapQueryStringCleanupComponents.json, tests/Functional/Fixtures/MapQueryStringController.json, tests/Functional/FunctionalTest.php, tests/Functional/SymfonyFunctionalTest.php
Fix from https://github.com/nelmio/NelmioApiDocBundle/pull/2178 solved proper describing of nullable enums for OAS v 3.0, but it seems that broke it for OAS v 3.1.
As for version 3.0 it's correct and looks like:
```
'nullableType' => [
'nullable' => true,
'allOf' => [
['$ref' => '#/components/schemas/ArticleType81'], // enum ref
],
],
```
for version 3.1 it seems to be wrong. It's impossible to match these both types at the same time:
```
'nullableType' => [
'allOf' => [
['$ref' => '#/components/schemas/ArticleType81'], // enum ref
['type' => 'null'],
]
],
```
I think the correct version for 3.1 should be:
```
'nullableType' => [
'oneOf' => [
['$ref' => '#/components/schemas/ArticleType81'], // enum ref
['type' => 'null'],
]
],
```
In our project we're validating API data responses …
=> fix: invalid nullable enums with OAS 3.1 version

src/ModelDescriber/ObjectModelDescriber.php
fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2237
=> fix: use iterable check instead of array

CHANGELOG.md, src/ModelDescriber/JMSModelDescriber.php, tests/Functional/Controller/JMSController80.php, tests/Functional/Controller/JMSController81.php, tests/Functional/Entity/DiscriminatorMap/JMSAbstractUser.php, tests/Functional/Entity/DiscriminatorMap/JMSAdministrator.php, tests/Functional/Entity/DiscriminatorMap/JMSManager.php, tests/Functional/JMSFunctionalTest.php
| New feature?  | yes                                                                  |
| Deprecations? | no                                               |
| Issues        |  |
This PR adds support for [JMS Discriminator](https://jmsyst.com/libs/serializer/master/reference/annotations#discriminator) to be able to implement [OpenAPI …
=> Support for JMS discriminator map

.github/workflows/common/composer-install/action.yaml, composer.json, tests/Functional/TestKernel.php
| Bug fix?      | no                                                                                                                   |
"Dropping" support for `sensio/framework-extra-bundle`
- It is abandoned
- It isn't actually being tested with this bundle
- It isn't used in this bundle
- There are no mentions of …
=> drop sensio/framework-extra-bundle

src/Describer/OpenApiPhpDescriber.php, tests/Functional/Controller/OperationIdController.php, tests/Functional/ControllerTest.php, tests/Functional/Fixtures/MapQueryStringCleanupComponents.json, tests/Functional/Fixtures/MapQueryStringController.json, tests/Functional/Fixtures/OperationIdController.json, tests/Functional/FunctionalTest.php
| Bug fix?      | yes                                                                                                                   |
| New feature?  | no                                                                  |
| Deprecations? | no                                                  |
| Issues        | --- |
*Current behaviour*
- OperationId is not generated when only using symfony attributes, e.g. #[Route]
- OperationId is not generated when only using one OA attributes, eg. #[Get] in combination …
=> fix: Generate operationids properly

src/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php
| Issues        | Fix #2275  |
https://github.com/nelmio/NelmioApiDocBundle/pull/2259 accidentally removed the `class_exists` check for symfony/validator `Constraint`. This currently causes applications using this …
=> fix: Unknown Constraint class when not using symfony/validator

src/ApiDocGenerator.php, src/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, src/ModelDescriber/ObjectModelDescriber.php, tests/Functional/Entity/VirtualProperty80.php, tests/Functional/Entity/VirtualProperty81.php, tests/Functional/ModelDescriber/NameConverter.php
| New feature?  | no                                             |
| Deprecations? | no                                             |
This apply the rule [TypedPropertyFromStrictConstructor](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#typedpropertyfromstrictconstructorrector)  over src and tests.
I plan to add more PR with more rules processed
=> feat: apply rule TypedPropertyFromStrictConstructor from rector

src/Controller/SwaggerUiController.php, tests/Functional/TestKernel.php
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | -
Currently the `SwaggerUiController` doesn't respect the `assets_mode` configuration added in #2251.
```yaml
nelmio_api_doc:
html_config:
assets_mode: cdn
```
As far as I can tell, there's no reason for the default any more as it can be set through the configuration and overridden in the `DumpCommand` command using the `html-config` option.
=> Respect assets mode config in controller

src/ModelDescriber/JMSModelDescriber.php, tests/Functional/Controller/JMSController80.php, tests/Functional/Controller/JMSController81.php, tests/Functional/Entity/JMSTyped80.php, tests/Functional/Entity/JMSTyped81.php, tests/Functional/JMSFunctionalTest.php, tests/Functional/TestKernel.php
In the case of php7.4 typed properties for JMS serializer there is no difference between nullable typed property and required one:
```php
/**
* @Serializer\Type("integer")
*/
private int $id;
/**
* @Serializer\Type("string")
*/
private ?string $name;
```
Spec is generated for both properties as optional, but the `$id` must be required.
This PR adds support for marking fields as required automatically for php7.4 typed properties and for virtual properties based on their return type's nullability.
=> Support php7.4 nullable typed properties for JMS serializer.

.github/workflows/pr-lint.yml, CONTRIBUTING.md
| Q             | A           |
|---------------|-------------|
| Bug fix?      | no          |
| New feature?  | no          |
| Deprecations? | no          |
| Issues        | Close #2264 |
* Adds a GitHub Actions workflow (based on [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request)) validating PR titles for compliance with the [Conventional Commits](https://www.conventionalcommits.org/) specification.
=> docs(#2264): adopt Conventional Commits

src/PropertyDescriber/UuidPropertyDescriber.php
| New feature?  | yes/no                                                                    |
| Deprecations? | yes/no                                                   |
| Issues        | Fix #2300  |
Fixes deprecation warning from missing `context` parameter on `UuidPropertyDescriber::describe()`
=> fix(#2300): fix missing context param UuidPropertyDescriber::describe()

docs/customization.rst
the link that was there no longer worked, it led to a file that hadn't existed for a while, so I updated it
| Deprecations? | yes                                                   |
=> docs: update link to index.html.twig in customization.rst

src/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php, tests/Functional/Entity/SymfonyConstraintsWithValidationGroups80.php, tests/Functional/Entity/SymfonyConstraintsWithValidationGroups81.php, tests/Functional/Fixtures/MapQueryStringCleanupComponents.json, tests/Functional/Fixtures/MapQueryStringController.json, tests/Functional/Fixtures/MapRequestPayloadController.json, tests/Functional/ValidationGroupsFunctionalTest.php
| Issues        | Fix #2309 |
if a property is set as something like this:
```php
#[OA\Property()]
#[Assert\NotNull(groups: ['validation'])]
private ?string $prop = null;
```
that property will be marked as …
=> fix(SymfonyConstraintAnnotationReader): disallow null if NotNull attribute is present

src/OpenApiPhp/Util.php
| Bug fix?      | yes                                                                                                                   |
| Issues        | Fix #2336  |
The original implementation lost the original key index because it created a new array (with `array_column`).
https://3v4l.org/kWPt7#v8.3.10
=> fix(#2336): keep original index key

CHANGELOG.md, src/Describer/OpenApiPhpDescriber.php, src/OpenApiPhp/Util.php, tests/Functional/Controller/OpenApiTagController.php, tests/Functional/ControllerTest.php, tests/Functional/Fixtures/OpenApiTagController.json, tests/SwaggerPhp/UtilTest.php
Close #2333
| New feature?  | yes                                                                    |
| Issues        | Fix #2333  |
When processing `OA\Tag` annotation inside the `OpenApiPhpDescriber`, the corresponding top level OpenApi Tag is created on the fly, so the description and the …
=> feat: create top level Tag from Tag annotations

.php-cs-fixer.dist.php, tests/Functional/ControllerTest.php
Trying to get a green build again. Apparently it started failing somewhen between August and September. Not checking in composer.lock is risky, especially with tooling like PHPStan …
=> chore: fix ci

src/ModelDescriber/ApplyOpenApiDiscriminatorTrait.php, src/ModelDescriber/BazingaHateoasModelDescriber.php, src/ModelDescriber/JMSModelDescriber.php
| New feature?  | o                                                                    |
I noticed that information I'm adding into a JMS serializer model gets lost inside it because `serializationContext` is not passed through everywhere, but it most likely should? the …
=> fix: pass through serializationContext into models where possible

docs/index.rst
| Bug fix?      | yes/no                                                                                                                    |
just a small docs fix I noticed on https://symfony.com/bundles/NelmioApiDocBundle/current/index.html
=> docs: use rst inline literal instead of invalid Markdown code

.github/workflows/common/composer-install/action.yaml, .github/workflows/continuous-integration.yml
ci: [5.x] codecov (#2365)
Adds codecov to ci
=> ci: [4.x] codecov

CHANGELOG.md, docs/alternative_names.rst, docs/areas.rst, docs/faq.rst, docs/index.rst, docs/security.rst, phpstan-baseline.neon, phpunit-ignore.txt, src/Annotation/Areas.php, src/Annotation/Model.php, src/Annotation/Operation.php, src/Annotation/Security.php, src/Attribute/Areas.php, src/Attribute/Model.php, src/Attribute/Operation.php, src/Attribute/Security.php, src/Describer/OpenApiPhpDescriber.php, src/OpenApiPhp/ModelRegister.php, src/Routing/FilteredRouteCollectionBuilder.php
| Deprecations? | yes                                                  |
Migration for annotations to attributes https://github.com/nelmio/NelmioApiDocBundle/pull/2368#discussion_r1816553558
=> feat: 4.x annotation to attribute migration 5.x

src/ModelDescriber/EnumModelDescriber.php, src/ModelDescriber/JMSModelDescriber.php, tests/Functional/Entity/JMSEnum81.php, tests/Functional/JMSFunctionalTest.php
| Bug fix?      | no                                                                                                                   |
| New feature?  | yes                                                                    |
| Issues        | -  |
This PR add a method to detect when the developer has annotated their property with a JMS type that specifies that the backed enum needs to be serialized with its name instead of value. I …
=> feat: add support for name based serialisation of JMS enums

src/ModelDescriber/FormModelDescriber.php
Refactor `FormModelDescriber`:
- Remove default values from constructor params
- The class is marked as internal so default params are not needed as we can rely on DI
- Removed impossible deprecation `$mediaTypes` is not nullable
- Removed impossible exception `$formFactory` could never be `null`
=> refactor: remove deprecation & thrown exception & constructor defaults

src/ModelDescriber/Annotations/AnnotationsReader.php, src/ModelDescriber/Annotations/ReflectionReader.php, src/ModelDescriber/ObjectModelDescriber.php, tests/Functional/FunctionalTest.php, tests/Functional/JMSFunctionalTest.php
This change allows that defaults that are set in attributes can override the ones that are read from the code.
This fixes https://github.com/nelmio/NelmioApiDocBundle/issues/2330
Closes #2330
=> fix: override code based defaults with explicit ones

.github/workflows/continuous-integration.yml
@dependabot does not have access to the `CODECOV_TOKEN` which is causing the codecov job to fail in https://github.com/nelmio/NelmioApiDocBundle/pull/2383 for example.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#adding-an-organization-secret-for-dependabot
=> ci: skip codecov upload for dependabot

.github/workflows/continuous-integration.yml, CHANGELOG.md, phpunit-ignore.txt, phpunit.xml.dist, src/Attribute/Model.php, src/Model/Model.php, src/Model/ModelRegistry.php, src/ModelDescriber/FormModelDescriber.php, src/ModelDescriber/JMSModelDescriber.php, src/PropertyDescriber/ObjectPropertyDescriber.php, tests/Functional/Controller/DeprecationController.php, tests/Functional/ControllerTest.php, tests/Functional/Fixtures/DeprecationController.json, tests/Model/ModelRegistryTest.php
Deprecates `options` nullable type for `Model` classes. This reduces complexity and streamlines it with the `$serializationContext`.
=> refactor: deprecate `options` possibly being null

CHANGELOG.md, phpstan-baseline.neon, src/ModelDescriber/ObjectModelDescriber.php, src/PropertyDescriber/ArrayPropertyDescriber.php, src/PropertyDescriber/BooleanPropertyDescriber.php, src/PropertyDescriber/CompoundPropertyDescriber.php, src/PropertyDescriber/DateTimePropertyDescriber.php, src/PropertyDescriber/DictionaryPropertyDescriber.php, src/PropertyDescriber/FloatPropertyDescriber.php, src/PropertyDescriber/IntegerPropertyDescriber.php, src/PropertyDescriber/NullablePropertyDescriber.php, src/PropertyDescriber/ObjectPropertyDescriber.php, src/PropertyDescriber/PropertyDescriber.php, src/PropertyDescriber/PropertyDescriberInterface.php, src/PropertyDescriber/RequiredPropertyDescriber.php, src/PropertyDescriber/StringPropertyDescriber.php, src/PropertyDescriber/UuidPropertyDescriber.php
https://github.com/nelmio/NelmioApiDocBundle/pull/2388#discussion_r1838271248
=> refactor: add $context to PropertyDescriberInterface::supports()

UPGRADE-5.0.md, src/Command/DumpCommand.php, src/PropertyDescriber/ArrayPropertyDescriber.php, src/PropertyDescriber/BooleanPropertyDescriber.php, src/PropertyDescriber/CompoundPropertyDescriber.php, src/PropertyDescriber/DateTimePropertyDescriber.php, src/PropertyDescriber/FloatPropertyDescriber.php, src/PropertyDescriber/IntegerPropertyDescriber.php, src/PropertyDescriber/ObjectPropertyDescriber.php, src/PropertyDescriber/StringPropertyDescriber.php
Make classes marked with `@final` final
https://github.com/nelmio/NelmioApiDocBundle/issues/2215
=> refactor: [5.x] finalize class

UPGRADE-5.0.md, src/Describer/DescriberInterface.php, src/Describer/ExternalDocDescriber.php, src/Describer/ModelRegistryAwareInterface.php, src/Describer/ModelRegistryAwareTrait.php, src/ModelDescriber/BazingaHateoasModelDescriber.php, src/ModelDescriber/EnumModelDescriber.php, src/ModelDescriber/FallbackObjectModelDescriber.php, src/ModelDescriber/JMSModelDescriber.php, src/ModelDescriber/ModelDescriberInterface.php, src/ModelDescriber/ObjectModelDescriber.php, src/PropertyDescriber/ArrayPropertyDescriber.php, src/PropertyDescriber/BooleanPropertyDescriber.php, src/PropertyDescriber/CompoundPropertyDescriber.php, src/PropertyDescriber/DateTimePropertyDescriber.php, src/PropertyDescriber/DictionaryPropertyDescriber.php, src/PropertyDescriber/FloatPropertyDescriber.php, src/PropertyDescriber/IntegerPropertyDescriber.php, src/PropertyDescriber/NullablePropertyDescriber.php, src/PropertyDescriber/ObjectPropertyDescriber.php, src/PropertyDescriber/PropertyDescriberInterface.php, src/PropertyDescriber/StringPropertyDescriber.php, src/PropertyDescriber/UuidPropertyDescriber.php, src/RouteDescriber/RouteDescriberInterface.php, tests/Functional/ModelDescriber/VirtualTypeClassDoesNotExistsHandlerDefinedDescriber.php
Add void return types where possible
=> refactor: [5.x] add void return types

.php-cs-fixer.dist.php, src/Attribute/Model.php, src/Attribute/Security.php, src/ModelDescriber/Annotations/AnnotationsReader.php, src/ModelDescriber/Annotations/ReflectionReader.php, src/ModelDescriber/ApplyOpenApiDiscriminatorTrait.php, src/ModelDescriber/FormModelDescriber.php, src/ModelDescriber/JMSModelDescriber.php, src/ModelDescriber/ObjectModelDescriber.php, src/OpenApiPhp/ModelRegister.php, src/OpenApiPhp/Util.php, src/PropertyDescriber/PropertyDescriber.php, src/RouteDescriber/RouteArgumentDescriber.php, src/Routing/FilteredRouteCollectionBuilder.php, tests/Functional/Controller/ApiController.php, tests/Functional/Controller/MapQueryStringController.php, tests/Functional/JMSFunctionalTest.php, tests/Routing/FilteredRouteCollectionBuilderTest.php
Adds `mixed` php type in code & allows trailing comma's to be used in [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer)
=> refactor: [5.x] mixed types & trailing comma

tests/Command/DumpCommandTest.php, tests/Model/ModelRegistryTest.php
=> style: use `@PHP84Migration` ruleset

CHANGELOG.md, config/services.xml
I now get this error on a 7.2 project:
> Since symfony/dependency-injection 7.2: Type "tagged" is deprecated for tag <argument>, use "tagged_iterator" instead in ".../vendor/nelmio/api-doc-bundle/src/DependencyInjection/../../config/services.xml".
tagged_iterator exists on https://symfony.com/doc/5.x/service_container/tags.html so I believe this is safe to use already for v4 / symfony 5.4+.
=> Remove deprecate use of tagged argument in favor of tagged_iterator

src/ModelDescriber/Annotations/ReflectionReader.php
When reflection shows that the default parameter of a a property is null, then the `nullable` parameter is set to `true` for that property.
Currently that needs to be set via the attribute but that is a bit redundant as the information is already available from reflection
This change only does that for properties and for setter methods.
Right now getter methods that allow a null value to be returned are not taken into account for setting the `nullable` property.
This resets the state prior to v4.25.0 and is related to #2330
This is a refactor of #2377
=> fix: set nullable true when default value is null

src/DependencyInjection/Compiler/CustomProcessorPass.php, tests/Functional/Configs/StubProcessor.yaml, tests/Functional/ControllerTest.php, tests/Functional/StubProcessor.php
The before implementation was never functional, as the returned tags array is a tag name indexed array of tags. This change resolves that, and adds a test to actually insert a processor with the before attribute.
=> fix: before implementation with custom processors

composer.json, src/ApiDocGenerator.php, src/DependencyInjection/Compiler/CustomProcessorPass.php, src/DependencyInjection/NelmioApiDocExtension.php, src/OpenApiGenerator.php
zircote/swagger-php v5 has been released, and seems to only require minimal updates. See https://github.com/zircote/swagger-php/blob/master/docs/guide/migrating-to-v5.md.
I did need to migrate the current processor implementation to the one that is using the new processor pipeline introduced with 4.10.0, which is why I bumped the minimum constraint. In order to not mess up dependency injection, I was required to wrap the Generator class in order to allow adding additional processors using the existing compiler pass.
=> chore: allow zircote/swagger-php v5

src/PropertyDescriber/ArrayPropertyDescriber.php, src/PropertyDescriber/BooleanPropertyDescriber.php, src/PropertyDescriber/CompoundPropertyDescriber.php, src/PropertyDescriber/DateTimePropertyDescriber.php, src/PropertyDescriber/FloatPropertyDescriber.php, src/PropertyDescriber/IntegerPropertyDescriber.php, src/PropertyDescriber/ObjectPropertyDescriber.php, src/PropertyDescriber/StringPropertyDescriber.php
Marks non-final PropertyDescribers  with `@final` in preparation for 5.x
=> fix: mark PropertyDescribers with @final

docs/index.rst
Update link to 5.x upgrade guide
=> docs: migration docs 5.x

docs/configuration_reference.rst, docs/index.rst
Adds documentation for the various config options
=> docs: configuration reference

config/services.xml
Fixes deprecation warning for usage of "tagged" that got added with https://github.com/nelmio/NelmioApiDocBundle/pull/2349
https://github.com/nelmio/NelmioApiDocBundle/pull/2410
=> fix: deprecation warning for usage of "tagged"

CHANGELOG.md, phpunit-ignore.txt, src/Attribute/Areas.php, tests/Attribute/AreasTest.php, tests/Routing/FilteredRouteCollectionBuilderTest.php
Cleans up the `Area` annotation/attribute to trigger a deprecation warning whenever a list of strings isn't passed.
=> chore: cleanup Areas annotation

templates/Stoplight/index.html.twig, tests/Command/DumpCommandTest.php
Fixes stoplight ui on massive documentation
https://docs.stoplight.io/docs/elements/d536b917a4e1d-layout
=> fix: stoplight ui height
